import { DEFAULT_SETTINGS, type SettingsState } from "@/lib/settings";

export type SettingKey = keyof typeof DEFAULT_SETTINGS;
export interface SettingDefinition {
  id: string;
  tabId: string;
  title: string;
  description: string;
  keywords: readonly string[];
  key?: SettingKey;
}

export const SETTINGS_CATALOG: readonly SettingDefinition[] = [
  {
    id: "easy-mode",
    tabId: "general",
    title: "Easy Mode",
    description:
      "Weniger Ablenkung: Blendet MCP, Versionierung, Monitor, geteilte Ansichten und weitere Verwaltungswerkzeuge aus. Deine Arbeitsstände bleiben erhalten.",
    keywords: ["einfach", "anfänger", "mcp", "versionierung", "monitor", "split"],
    key: "easyMode",
  },
  {
    id: "theme",
    tabId: "appearance",
    title: "Erscheinungsbild",
    description: "Hell, dunkel oder dem System folgen.",
    keywords: ["theme", "dark", "light", "system", "farbe", "modus", "hell", "dunkel"],
  },
  {
    id: "filter-operators",
    tabId: "general",
    title: "Filteroperatoren übersetzen",
    description:
      "Bezeichnungen wie „ist gleich“ anzeigen. Ausgeschaltet erscheinen =, <>, IN, IS NULL und LIKE-Muster bzw. die nativen Operatoren der Datenbank.",
    keywords: [
      "filter",
      "operatoren",
      "übersetzen",
      "sql",
      "gleich",
      "like",
      "in",
      "not in",
      "null",
    ],
    key: "translateFilterOperators",
  },
  {
    id: "hide-own-schema",
    tabId: "general",
    title: "Eigenes Schema ohne Auswahl",
    description:
      "Blendet die Schema-Auswahl in der Seitenleiste aus, wenn das aktive Schema dem Benutzernamen der Verbindung entspricht.",
    keywords: ["schema", "benutzer", "user", "auswahl", "sidebar", "oracle"],
    key: "hideOwnSchemaSelect",
  },
  {
    id: "sidebar-object-nav",
    tabId: "general",
    title: "Objekttypen in der Seitenleiste",
    description:
      "Tabellen, Views, Funktionen und weitere Objekttypen als Icon-Leiste oder als beschriftete Auswahl über der Liste wechseln.",
    keywords: ["sidebar", "seitenleiste", "tabbar", "tabs", "auswahl", "select", "objekttyp"],
    key: "sidebarObjectNav",
  },
  {
    id: "onboarding",
    tabId: "general",
    title: "Onboarding",
    description: "Intro, Theme- und Moduswahl vom ersten Start erneut anzeigen.",
    keywords: [],
  },
  {
    id: "reset",
    tabId: "general",
    title: "Werkseinstellungen",
    description: "Alle Optionen auf die ursprünglichen Standardwerte zurücksetzen.",
    keywords: ["reset", "werkseinstellungen", "standard", "löschen", "zurücksetzen"],
  },
  {
    id: "cli-install",
    tabId: "cli",
    title: "Befehl „l8db“ im Terminal",
    description:
      "Macht „l8db“ in jedem Terminal verfügbar. Die CLI nutzt deine gespeicherten Verbindungen samt SSH-Tunnel und Schlüsselbund.",
    keywords: [
      "cli",
      "terminal",
      "kommandozeile",
      "shell",
      "konsole",
      "path",
      "befehl",
      "installieren",
    ],
  },
  {
    id: "cli-cheatsheet",
    tabId: "cli",
    title: "Erste Schritte",
    description:
      "Die wichtigsten Befehle zum Kopieren. Jeder Befehl erklärt sich mit --help selbst.",
    keywords: [
      "cli",
      "terminal",
      "befehle",
      "beispiele",
      "spickzettel",
      "query",
      "sql",
      "csv",
      "json",
    ],
  },
  {
    id: "cli-completions",
    tabId: "cli",
    title: "Tab-Vervollständigung",
    description:
      "Befehle, Optionen und Formate per Tab-Taste ergänzen. Einmal einrichten, dann ein neues Terminal öffnen.",
    keywords: ["cli", "completion", "autovervollständigung", "zsh", "bash", "fish", "powershell"],
  },
  {
    id: "ui-scale",
    tabId: "appearance",
    title: "Oberflächengröße",
    description:
      "Schrift, Symbole und Bedienelemente in der gesamten App verkleinern oder vergrößern (80–150 %). Die Code-Schrift bleibt separat im SQL-Editor einstellbar.",
    keywords: [
      "größe",
      "grösse",
      "zoom",
      "skalierung",
      "kleiner",
      "größer",
      "schrift",
      "lesbarkeit",
      "oberfläche",
    ],
    key: "uiScale",
  },
  {
    id: "density",
    tabId: "appearance",
    title: "UI-Dichte",
    description:
      "Zeilenhöhen und Abstände in Seitenleiste, Tabellen, Menüs und Steuerelementen. Die Schriftgröße bleibt gleich.",
    keywords: [
      "dichte",
      "abstand",
      "kompakt",
      "spacious",
      "layout",
      "kompaktheit",
      "zeilenhöhe",
      "seitenleiste",
    ],
    key: "uiDensity",
  },
  {
    id: "sidebar-extra-compact",
    tabId: "appearance",
    title: "Seitenleiste extra kompakt",
    description:
      "Objektlisten ohne Zwischenräume und mit 20 px Zeilenhöhe bei 100 %. Die Schriftgröße bleibt erhalten. Gilt unabhängig von der UI-Dichte.",
    keywords: ["sidebar", "seitenleiste", "dichter", "kompakt", "abstände", "zeilenhöhe"],
    key: "sidebarExtraCompact",
  },
  {
    id: "nav-in-header",
    tabId: "appearance",
    title: "Navigation im Header",
    description: "Bereiche wie früher oben im Header statt in der Leiste am linken Rand anzeigen.",
    keywords: ["navigation", "header", "leiste", "rail", "bereiche", "layout"],
    key: "navInHeader",
  },
  {
    id: "dynamic-island",
    tabId: "appearance",
    title: "Dynamic Island",
    description:
      "Die Suche im Header zeigt Ladezustände, Update-Installationen, Begrüßungen und kleine Überraschungen. Ein Klick öffnet weiterhin die Suche.",
    keywords: [
      "dynamic island",
      "insel",
      "suche",
      "header",
      "begrüßung",
      "laden",
      "update",
      "animation",
    ],
    key: "dynamicIsland",
  },
  {
    id: "fit-columns-to-header",
    tabId: "appearance",
    title: "An Spaltentitel anpassen",
    description:
      "Tabellenspalten im klassischen Tabellenstil automatisch so breit darstellen, dass der Spaltentitel vollständig sichtbar ist.",
    keywords: [],
    key: "fitColumnsToHeader",
  },
  {
    id: "monochrome-cells",
    tabId: "appearance",
    title: "Einfarbige Tabellenwerte",
    description:
      "Zellwerte schwarz bzw. im Darkmode weiß anzeigen statt nach Datentyp einzufärben.",
    keywords: [],
    key: "monochromeCells",
  },
  {
    id: "table-style",
    tabId: "appearance",
    title: "Tabellenstil",
    description:
      "Wie Tabellen dargestellt werden: klassisch, kompakt mit Spaltenbreite nach Inhalt, semantisch nach Datentyp oder mit Spaltenprofil im Kopf.",
    keywords: [
      "tabelle",
      "grid",
      "stil",
      "design",
      "kompakt",
      "semantisch",
      "profil",
      "spalten",
      "übersicht",
      "dichte",
    ],
    key: "tableStyle",
  },
  {
    id: "reset-appearance",
    tabId: "appearance",
    title: "Darstellung zurücksetzen",
    description:
      "Oberflächengröße, UI-Dichte, Spaltenbreiten und Seitenleistenabstände auf Standard zurücksetzen. Änderungen werden sofort angewendet und gespeichert.",
    keywords: [],
  },
  {
    id: "history-limit",
    tabId: "data",
    title: "Query-Verlauf je Verbindung",
    description:
      "50 bis 5000 Einträge. Ältere Einträge werden entfernt; dauerhaft gespeicherte Queries bleiben erhalten.",
    keywords: [],
  },
  {
    id: "row-limit",
    tabId: "data",
    title: "Standard-Zeilenlimit",
    description: "Maximale Anzahl abgerufener Datensätze pro Tabelle (10 bis 5000).",
    keywords: ["limit", "zeilen", "records", "datensätze", "rows", "tabelle"],
    key: "rowLimit",
  },
  {
    id: "timeout",
    tabId: "data",
    title: "Query-Timeout",
    description:
      "Zeitgrenze für SQL-Ausführungen (5 bis 300 Sekunden). PostgreSQL und SQLite können den Abbruch bestätigen; bei anderen Treibern muss nach einem Timeout der Serverzustand geprüft werden.",
    keywords: ["timeout", "zeit", "abfrage", "dauer", "abbruch", "sekunden"],
    key: "queryTimeout",
  },
  {
    id: "transactions",
    tabId: "data",
    title: "Änderungen als Transaktion (Safe Mode)",
    description: "Zeilenänderungen und DML sammeln und erst nach manuellem Commit persistieren.",
    keywords: [],
    key: "transactionsEnabled",
  },
  {
    id: "destructive-confirm",
    tabId: "data",
    title: "Destruktive Abfragen absichern",
    description: "Bestätigungsdialog vor DROP TABLE, TRUNCATE oder DELETE ohne WHERE-Klausel.",
    keywords: ["drop", "truncate", "delete", "warnung", "sicherheit", "bestätigung"],
    key: "confirmDestructiveQueries",
  },
  {
    id: "multi-target",
    tabId: "data",
    title: "Abfrage auf mehreren Zielen",
    description:
      "Wie viele Ziele gleichzeitig abgefragt werden (1 bis 16), wie viele Zeilen je Ziel geladen werden und wann ein Ziel abbricht.",
    keywords: ["mehrere", "ziele", "datenbanken", "tenant", "parallel", "gleichzeitig", "fan-out"],
    key: "multiTargetConcurrency",
  },
  {
    id: "null-values",
    tabId: "data",
    title: "NULL-Werte hervorheben",
    description: "NULL-Werte im Tabellengitter optisch klar von leeren Zeichenketten trennen.",
    keywords: ["null", "hervorheben", "darstellung", "gitter", "tabelle", "leer"],
    key: "highlightNullValues",
  },
  {
    id: "transfer",
    tabId: "data",
    title: "Transfer",
    description:
      "Komplette Schemas mit Struktur und Daten in eine andere Verbindung kopieren, auch zwischen Datenbankfamilien.",
    keywords: ["transfer", "kopieren", "migration", "migrieren", "datenbank", "übertragen"],
  },
  {
    id: "ssh-tofu",
    tabId: "security",
    title: "Neue SSH-Host-Keys akzeptieren",
    description:
      "Unbekannte Server-Schlüssel beim ersten Verbindungsaufbau automatisch speichern (TOFU).",
    keywords: ["ssh", "host", "keys", "fingerprint", "tofu", "trust"],
    key: "sshTrustNewHosts",
  },
  {
    id: "production-read-only",
    tabId: "security",
    title: "Produktion standardmäßig schreibgeschützt öffnen",
    description:
      "Verbindungen mit Umgebung Produktion sind schreibgeschützt, bis im Banner der Schreibmodus für 15 Minuten aktiviert wird.",
    keywords: ["produktion", "umgebung", "schreibschutz", "prod", "guardrail", "schreibmodus"],
    key: "productionReadOnly",
  },
  {
    id: "production-commit",
    tabId: "security",
    title: "Commits auf Produktion bestätigen",
    description:
      "Jeder Commit auf Produktion braucht eine Bestätigung. Löschungen und destruktive Anweisungen verlangen immer die Eingabe des Verbindungsnamens.",
    keywords: ["produktion", "commit", "bestätigen", "transaktion", "rollback"],
    key: "productionConfirmCommit",
  },
  {
    id: "production-auto-rollback",
    tabId: "security",
    title: "Offene Produktions-Transaktionen automatisch zurückrollen",
    description:
      "Beim Ablauf oder Beenden des Schreibmodus werden offene Transaktionen der Verbindung zurückgerollt.",
    keywords: [],
    key: "productionAutoRollback",
  },
  {
    id: "dml-preview",
    tabId: "security",
    title: "Vorschau vor UPDATE und DELETE",
    description:
      "Zeigt vor dem Ausführen, welche und wie viele Zeilen ein UPDATE, DELETE, MERGE oder INSERT … SELECT betrifft. Die Vorschau liest nur und sperrt keine Zeilen.",
    keywords: [
      "vorschau",
      "preview",
      "update",
      "delete",
      "merge",
      "betroffene zeilen",
      "produktion",
    ],
    key: "dmlPreviewMode",
  },
  {
    id: "dml-preview-limits",
    tabId: "security",
    title: "Grenzen der DML-Vorschau",
    description:
      "Maximale Beispielzeilen, Zeitlimit der Vorschau-Abfragen und ab wie vielen betroffenen Zeilen deutlich gewarnt wird.",
    keywords: ["vorschau", "zeilen", "timeout", "warnung", "schwelle", "limit"],
  },
  {
    id: "conn-timeout",
    tabId: "security",
    title: "Verbindungs-Timeout",
    description: "Maximale Wartezeit beim Verbindungsaufbau zur Datenbank (3 bis 60 Sekunden).",
    keywords: ["verbindung", "timeout", "netzwerk", "connect"],
    key: "connectionTimeout",
  },
  {
    id: "ssl-mode",
    tabId: "security",
    title: "Standard-SSL-Modus",
    description: "Standardmäßige TLS/SSL-Anforderung für neue Datenbankverbindungen.",
    keywords: ["ssl", "tls", "zertifikat", "verschlüsselung", "prefer", "require"],
    key: "sslDefaultMode",
  },
  {
    id: "about",
    tabId: "about",
    title: "Über l8db",
    description: "Informationen zur App, Funktionen und Technologien.",
    keywords: ["über", "about", "l8db", "funktionen", "technologien"],
  },
  {
    id: "documentation",
    tabId: "about",
    title: "Dokumentation",
    description: "Anleitungen zu Verbindungen, Query-Editor und Installation im Browser öffnen.",
    keywords: [],
  },
  {
    id: "open-source-licenses",
    tabId: "about",
    title: "Open-Source-Lizenzen",
    description:
      "l8db ist Open Source unter der Apache License 2.0. Lizenzen aller enthaltenen Komponenten anzeigen.",
    keywords: [],
  },
  {
    id: "diagnostics",
    tabId: "about",
    title: "Systemdiagnose",
    description: "Laufzeitumgebung und Debug-Informationen für Support oder Fehlerberichte.",
    keywords: ["diagnose", "system", "info", "kopieren", "fehlerbericht", "support"],
  },
  {
    id: "crash-reports",
    tabId: "about",
    title: "Absturzberichte senden",
    description:
      "Abstürze mit Fehlermeldung, Stacktrace, Version und Betriebssystem sowie Warn- und Fehlerprotokolle und die letzten Befehlsnamen an Sentry (EU) senden. Verbindungsdaten werden entfernt, SQL und Ergebnisdaten nie gesendet.",
    keywords: [
      "absturz",
      "crash",
      "sentry",
      "telemetrie",
      "datenschutz",
      "fehlerbericht",
      "logs",
      "protokoll",
    ],
    key: "crashReports",
  },
  {
    id: "usage-metrics",
    tabId: "about",
    title: "Nutzungs- und Leistungsdaten senden",
    description:
      "Bereiche, Bedienwege, aktive Vordergrundzeit, Sitzungen, Startzeit sowie Erfolg, Fehler, Abbrüche und Dauer von Datenbankbefehlen je DB-Typ (auch als Traces mit Ladezeiten) an Sentry (EU) senden. Nie SQL, Ergebnisdaten, Namen oder Verbindungsdaten.",
    keywords: [
      "metriken",
      "metrics",
      "nutzung",
      "leistung",
      "performance",
      "telemetrie",
      "sentry",
      "traces",
      "tracing",
    ],
    key: "usageMetrics",
  },
  {
    id: "local-usage-statistics",
    tabId: "statistics",
    title: "Lokale Nutzungsstatistik erfassen",
    description:
      "Bereiche, Bedienwege, aktive Vordergrundzeit und Datenbankvorgänge dieser Installation für die letzten 32 Fenstersitzungen lokal erfassen. Ausschalten pausiert die Erfassung und behält bisherige Werte.",
    keywords: ["statistik", "nutzung", "lokal", "sitzungen", "aktivität", "bedienwege", "leistung"],
    key: "localUsageStats",
  },
  {
    id: "bug-report",
    tabId: "about",
    title: "Bug melden",
    description:
      "Problem beschreiben und direkt auf GitHub melden, kopieren oder per E-Mail senden.",
    keywords: ["bug", "fehler", "melden", "report", "github", "issue", "email", "mail", "support"],
  },
  {
    id: "update-channel",
    tabId: "about",
    title: "Update-Kanal",
    description:
      "Stable erhält nur geprüfte Versionen. Canary erhält neue Versionen früher, ohne Gewähr.",
    keywords: ["canary", "stable", "beta", "vorabversion", "kanal", "channel", "updates"],
    key: "updateChannel",
  },
  {
    id: "updates",
    tabId: "about",
    title: "Automatisch nach Updates suchen",
    description: "Beim Start und danach alle 6 Stunden im Hintergrund nach neuen Versionen suchen.",
    keywords: [],
    key: "autoUpdateCheck",
  },
  {
    id: "auto-update-install",
    tabId: "about",
    title: "Updates automatisch installieren",
    description: "Gefundene Updates ohne Rückfrage installieren und neu starten.",
    keywords: [],
    key: "autoUpdateInstall",
  },
  {
    id: "feature-videos",
    tabId: "about",
    title: "Neue Features als Video",
    description: "Wichtige Neuerungen unten rechts automatisch stumm zeigen. Jederzeit schließbar.",
    keywords: ["video", "features", "neu", "autoplay", "vorstellung"],
    key: "autoFeatureVideos",
  },
  {
    id: "release-notes",
    tabId: "about",
    title: "Release Notes",
    description: "Änderungen aller veröffentlichten Versionen.",
    keywords: ["release", "notes", "changelog", "änderungen", "versionen"],
  },
  {
    id: "update-status",
    tabId: "about",
    title: "Updates",
    description: "Du nutzt die aktuelle Version.",
    keywords: [],
  },
  {
    id: "tour",
    tabId: "general",
    title: "Produkttour",
    description:
      "Kapitelweise Führung durch Verbindungen, Explorer, SQL und Einstellungen. Startet immer bei Kapitel 1.",
    keywords: ["tour", "anleitung", "hilfe", "einführung", "walkthrough", "tutorial"],
  },
  {
    id: "editor-quick-suggestions",
    tabId: "editor",
    title: "Vorschläge beim Tippen",
    description: "Vorschlagsliste automatisch während der Eingabe öffnen.",
    keywords: [],
    key: "editorQuickSuggestions",
  },
  {
    id: "editor-suggest-on-trigger-characters",
    tabId: "editor",
    title: "Trigger-Zeichen",
    description: "Vorschläge nach Zeichen wie dem Punkt (schema.tabelle) öffnen.",
    keywords: [],
    key: "editorSuggestOnTriggerCharacters",
  },
  {
    id: "suggest-delay",
    tabId: "editor",
    title: "Verzögerung",
    description: "Wartezeit bis Vorschläge erscheinen (0 bis 500 ms).",
    keywords: [],
    key: "editorSuggestDelay",
  },
  {
    id: "editor-accept-suggestion-on-enter",
    tabId: "editor",
    title: "Enter übernimmt Vorschlag",
    description: "Markierter Vorschlag wird mit Enter eingefügt.",
    keywords: [],
    key: "editorAcceptSuggestionOnEnter",
  },
  {
    id: "editor-tab-completion",
    tabId: "editor",
    title: "Tab-Vervollständigung",
    description: "Vorschläge zusätzlich per Tab-Taste einfügen.",
    keywords: [],
    key: "editorTabCompletion",
  },
  {
    id: "editor-parameter-hints",
    tabId: "editor",
    title: "Parameter-Hinweise",
    description:
      "Beim Aufruf von Funktionen, Prozeduren und Package-Routinen die Parameter einblenden und den aktuellen hervorheben.",
    keywords: ["signatur", "parameter", "prozedur", "package"],
    key: "editorParameterHints",
  },
  {
    id: "rulers",
    tabId: "editor",
    title: "Lineale",
    description: "Vertikale Hilfslinien bei Spalten, z. B. 80, 120. Leer lassen zum Deaktivieren.",
    keywords: [],
    key: "editorRulers",
  },
  {
    id: "editor-ai",
    tabId: "editor",
    title: "KI im Editor",
    description:
      "Ghost-Text, Bearbeiten mit ⌘I, KI-Aktionen im Kontextmenü und über Anweisungen. Nutzt den KI-Anbieter aus dem Chat.",
    keywords: ["ki", "ai", "cursor", "copilot", "assistent", "inline", "llm"],
  },
  {
    id: "editor-ai-inline",
    tabId: "editor",
    title: "Ghost-Text-Vorschläge",
    description:
      "Mehrzeilige KI-Vorschläge beim Tippen. Tab übernimmt, ⌘→ wortweise. Nur mit API- oder lokalem Anbieter.",
    keywords: ["ki", "ghost", "autocomplete", "vervollständigung", "tab", "vorschlag"],
  },
  {
    id: "editor-ai-delay",
    tabId: "editor",
    title: "Wartezeit für Ghost-Text",
    description: "Pause nach dem Tippen, bevor eine Anfrage gesendet wird. Länger spart Tokens.",
    keywords: ["ki", "debounce", "verzögerung", "tokens"],
  },
  {
    id: "editor-ai-codelens",
    tabId: "editor",
    title: "KI-Aktionen über Anweisungen",
    description: "Erklären, Optimieren und Bearbeiten direkt über jedem SQL-Statement.",
    keywords: ["ki", "codelens", "erklären", "optimieren"],
  },
  {
    id: "editor-ai-next-edit",
    tabId: "editor",
    title: "Umbenennung weiterführen",
    description:
      "Nach dem Umbenennen eines Alias oder Namens die übrigen Vorkommen der Anweisung per Tab anpassen. Läuft lokal ohne KI.",
    keywords: ["umbenennen", "alias", "rename", "next edit", "tab"],
  },
  {
    id: "editor-ai-profile",
    tabId: "editor",
    title: "Anbieter für den Editor",
    description: "Eigener KI-Anbieter für Editor-Funktionen, sonst der aktuelle aus dem Chat.",
    keywords: ["ki", "anbieter", "provider", "modell"],
  },
  {
    id: "editor-ai-fast-model",
    tabId: "editor",
    title: "Schnelles Modell",
    description:
      "Kleines Modell für Ghost-Text, Kommentare und Testdaten. Leer lassen für das Standardmodell. Größere Umbauten nutzen immer das Hauptmodell.",
    keywords: ["ki", "modell", "routing", "günstig", "schnell", "tokens"],
  },
  {
    id: "editor-ai-validate",
    tabId: "editor",
    title: "KI-Vorschläge prüfen",
    description:
      "Erzeugtes SQL lokal und per EXPLAIN ohne Ausführung prüfen und bei Fehlern einmal korrigieren lassen.",
    keywords: ["ki", "prüfen", "validieren", "explain", "korrektur"],
  },
  {
    id: "editor-ai-share-values",
    tabId: "editor",
    title: "Ergebniswerte an die KI senden",
    description:
      "Aus: Die KI sieht nur Spalten, Typen und Statistiken. An: zusätzlich einige Beispielzeilen (maskierte Spalten bleiben maskiert).",
    keywords: ["ki", "datenschutz", "privacy", "werte", "ergebnis"],
  },
  {
    id: "editor-ai-metrics",
    tabId: "editor",
    title: "KI-Verbrauch im Editor",
    description: "Tokens, Cache-Quote, Annahmequote und Antwortzeiten pro Aktion.",
    keywords: ["ki", "tokens", "kosten", "statistik", "cache"],
  },
  {
    id: "editor-font-family",
    tabId: "editor",
    title: "Schriftart",
    description: "Code-Schriftart für den SQL-Editor.",
    keywords: [],
    key: "editorFontFamily",
  },
  {
    id: "font-size",
    tabId: "editor",
    title: "Schriftgröße",
    description: "Größe der Code-Schriftart (10 bis 24 px).",
    keywords: ["font", "schrift", "größe", "fontsize", "textgröße", "editor"],
    key: "editorFontSize",
  },
  {
    id: "editor-font-ligatures",
    tabId: "editor",
    title: "Ligaturen",
    description: "Programmier-Ligaturen der Schriftart nutzen (→, ≠, ⇒).",
    keywords: [],
    key: "editorFontLigatures",
  },
  {
    id: "editor-line-height",
    tabId: "editor",
    title: "Zeilenhöhe",
    description: "Abstand zwischen den Zeilen als Vielfaches der Schriftgröße.",
    keywords: [],
    key: "editorLineHeight",
  },
  {
    id: "tab-size",
    tabId: "editor",
    title: "Einrückungsbreite",
    description: "Anzahl der Leerzeichen pro Tabulatorstufe.",
    keywords: ["tab", "einrückung", "indent", "spaces", "leerzeichen"],
    key: "editorTabSize",
  },
  {
    id: "line-numbers",
    tabId: "editor",
    title: "Zeilennummern",
    description: "Nummerierung am linken Rand des Editors anzeigen.",
    keywords: ["zeilen", "nummern", "linenumbers", "zeilennummerierung"],
    key: "editorLineNumbers",
  },
  {
    id: "word-wrap",
    tabId: "editor",
    title: "Automatischer Zeilenumbruch",
    description: "Lange SQL-Zeilen im Editor automatisch umbrechen.",
    keywords: ["wrap", "umbruch", "zeilenumbruch", "wordwrap"],
    key: "editorWordWrap",
  },
  {
    id: "editor-wrapping-indent",
    tabId: "editor",
    title: "Umbruch-Einrückung",
    description: "Einrückung umbrochener Fortsetzungszeilen.",
    keywords: [],
    key: "editorWrappingIndent",
  },
  {
    id: "minimap",
    tabId: "editor",
    title: "Code-Minimap",
    description: "Verkleinerte Übersicht des gesamten SQL-Skripts am rechten Rand.",
    keywords: ["minimap", "übersicht", "karte", "scroll"],
    key: "editorMinimap",
  },
  {
    id: "minimap-scale",
    tabId: "editor",
    title: "Minimap-Maßstab",
    description: "Darstellungsgröße der Minimap-Vorschau.",
    keywords: [],
    key: "editorMinimapScale",
  },
  {
    id: "editor-bracket-pair-colorization",
    tabId: "editor",
    title: "Klammer-Färbung",
    description: "Verschachtelte Klammern in unterschiedlichen Farben darstellen.",
    keywords: [],
    key: "editorBracketPairColorization",
  },
  {
    id: "editor-guides-bracket-pairs",
    tabId: "editor",
    title: "Klammer-Hilfslinien",
    description: "Vertikale Führungslinien für Klammerpaare anzeigen.",
    keywords: [],
    key: "editorGuidesBracketPairs",
  },
  {
    id: "editor-guides-indentation",
    tabId: "editor",
    title: "Einrückungs-Hilfslinien",
    description: "Vertikale Linien für Einrückungsebenen anzeigen.",
    keywords: [],
    key: "editorGuidesIndentation",
  },
  {
    id: "editor-render-whitespace",
    tabId: "editor",
    title: "Leerzeichen",
    description: "Unsichtbare Zeichen (Punkte, Pfeile) einblenden.",
    keywords: [],
    key: "editorRenderWhitespace",
  },
  {
    id: "editor-smooth-scrolling",
    tabId: "editor",
    title: "Sanftes Scrollen",
    description: "Animiertes statt sprunghaftes Scrollen im Editor.",
    keywords: [],
    key: "editorSmoothScrolling",
  },
  {
    id: "editor-keymap",
    tabId: "editor",
    title: "Tastaturmodus",
    description: "Vim wird erst beim Aktivieren nachgeladen und gilt für alle SQL-Editoren.",
    keywords: [],
    key: "editorKeymap",
  },
  {
    id: "keyword-case",
    tabId: "editor",
    title: "SQL-Keywords",
    description: "Automatische Groß- oder Kleinschreibung beim Formatieren.",
    keywords: ["keywords", "groß", "klein", "upper", "lower", "schreibweise", "format"],
    key: "editorKeywordCase",
  },
  {
    id: "editor-format-dense-operators",
    tabId: "editor",
    title: "Kompakte Operatoren",
    description: "Operatoren ohne Leerzeichen formatieren (a=1 statt a = 1).",
    keywords: [],
    key: "editorFormatDenseOperators",
  },
  {
    id: "editor-format-newline-before-semicolon",
    tabId: "editor",
    title: "Umbruch vor Semikolon",
    description: "Jedes Statement mit Zeilenumbruch vor dem Semikolon beenden.",
    keywords: [],
    key: "editorFormatNewlineBeforeSemicolon",
  },
  {
    id: "format-lines-between-queries",
    tabId: "editor",
    title: "Leerzeilen zwischen Queries",
    description: "Abstand zwischen einzelnen Statements nach dem Formatieren.",
    keywords: [],
    key: "editorFormatLinesBetweenQueries",
  },
  {
    id: "editor-format-on-paste",
    tabId: "editor",
    title: "Formatieren beim Einfügen",
    description: "Eingefügten SQL-Code automatisch formatieren.",
    keywords: [],
    key: "editorFormatOnPaste",
  },
  {
    id: "editor-format-on-type",
    tabId: "editor",
    title: "Formatieren beim Tippen",
    description: "Zeile beim Setzen des Semikolons automatisch formatieren.",
    keywords: [],
    key: "editorFormatOnType",
  },
  {
    id: "transactions-per-table",
    tabId: "data",
    title: "Transaktionen pro Tabelle",
    description: "Änderungen je Tabelle getrennt sammeln und abschließen.",
    keywords: ["commit", "safe", "transaktion"],
    key: "transactionsPerTable",
  },
  {
    id: "table-tabs",
    tabId: "general",
    title: "Tabbar für Tabellen & Views",
    description: "Sichtbare Tabs für Tabellen und Views festlegen.",
    keywords: ["tabs", "tabbar", "sichtbar"],
    key: "hiddenTableDetailTabs",
  },
  {
    id: "portable-workspace",
    tabId: "general",
    title: "Portable Arbeitsumgebung",
    description: "Einstellungen, Tastenkürzel und Layouts als JSON übertragen.",
    keywords: ["export", "import", "übertragen", "backup"],
  },
  {
    id: "keychain",
    tabId: "security",
    title: "OS-Schlüsselbund & Secrets",
    description: "Passwörter und SSH-Schlüssel werden über die native Keychain verwaltet.",
    keywords: ["keychain", "schlüsselbund", "passwort", "tresor", "geheimnis", "vault"],
  },
  {
    id: "extensions",
    tabId: "extensions",
    title: "Erweiterungen",
    description: "Erweiterungen installieren, freigeben und einrichten, etwa den Passwortmanager.",
    keywords: [
      "extension",
      "plugin",
      "erweiterung",
      "community",
      "paket",
      "installieren",
      "passwortmanager",
      "bitwarden",
      "1password",
      "keeper",
      "openbao",
      "vault",
      "keycloak",
      "sso",
      "firma",
      "team",
      "zugänge",
      "zugangsdaten",
    ],
  },
  {
    id: "hotkeys",
    tabId: "hotkeys",
    title: "Tastenkürzel",
    description: "Tastenbelegungen für die Befehle der Anwendung anpassen.",
    keywords: ["tastatur", "hotkey", "shortcut"],
  },
];

export const SETTINGS_BY_ID = new Map(SETTINGS_CATALOG.map((setting) => [setting.id, setting]));

export function isStoredSettingModified(setting: SettingDefinition, state: SettingsState): boolean {
  if (!setting.key) return false;
  return JSON.stringify(state[setting.key]) !== JSON.stringify(DEFAULT_SETTINGS[setting.key]);
}

export function resetStoredSetting(setting: SettingDefinition, state: SettingsState): void {
  const key = setting.key;
  if (!key) return;
  if (key === "hiddenTableDetailTabs") {
    state.resetTableDetailTabs();
    return;
  }
  const setter = state[`set${key[0].toUpperCase()}${key.slice(1)}` as keyof SettingsState];
  if (typeof setter === "function")
    (setter as (value: (typeof DEFAULT_SETTINGS)[SettingKey]) => void)(
      structuredClone(DEFAULT_SETTINGS[key]),
    );
}
