import * as monaco from "monaco-editor/editor/editor.api";

const transparent = "#00000000";

monaco.editor.defineTheme("l8db-light", {
  base: "vs",
  inherit: true,
  rules: [],
  colors: {
    "editor.background": transparent,
    "editor.lineHighlightBackground": "#64748b0c",
    "editor.selectionBackground": transparent,
    "editor.inactiveSelectionBackground": transparent,
    "editor.selectionHighlightBackground": "#add6ff80",
    "editor.lineHighlightBorder": transparent,
    "editorGutter.background": transparent,
    "editorOverviewRuler.background": transparent,
    "scrollbarSlider.background": "#64748b40",
    "editorStickyScroll.background": "#f4f5f7",
    "editorStickyScrollGutter.background": "#f4f5f7",
    "editorStickyScroll.border": "#e2e5ea",
    "editorStickyScroll.shadow": "#00000014",
    "editorStickyScrollHover.background": "#eceef1",
    "editorLink.activeForeground": "#2563eb",
    "menu.background": "#fdfeff",
    "menu.foreground": "#1b1e24",
    "menu.selectionBackground": "#1178c4",
    "menu.selectionForeground": "#ffffff",
    "menu.separatorBackground": "#11182714",
    "menu.border": "#11182724",
  },
});

monaco.editor.defineTheme("l8db-dark", {
  base: "vs-dark",
  inherit: true,
  rules: [],
  colors: {
    "editor.background": transparent,
    "editor.lineHighlightBackground": "#94a3b80c",
    "editor.selectionBackground": transparent,
    "editor.inactiveSelectionBackground": transparent,
    "editor.selectionHighlightBackground": "#add6ff26",
    "editor.lineHighlightBorder": transparent,
    "editorGutter.background": transparent,
    "editorOverviewRuler.background": transparent,
    "scrollbarSlider.background": "#94a3b840",
    "editorStickyScroll.background": "#1d1f2a",
    "editorStickyScrollGutter.background": "#1d1f2a",
    "editorStickyScroll.border": "#2e3345",
    "editorStickyScroll.shadow": "#00000066",
    "editorStickyScrollHover.background": "#262a3a",
    "editorLink.activeForeground": "#60a5fa",
    "menu.background": "#1b232a",
    "menu.foreground": "#e8eaee",
    "menu.selectionBackground": "#2b85cf",
    "menu.selectionForeground": "#ffffff",
    "menu.separatorBackground": "#ffffff14",
    "menu.border": "#000000b3",
  },
});
