import {
  ActivityIcon,
  AlignLeftIcon,
  ChartColumnIcon,
  ChartLineIcon,
  ChartPieIcon,
  CircleDotIcon,
  FilterIcon,
  GaugeIcon,
  Grid3x3Icon,
  HashIcon,
  LayoutGridIcon,
  type LucideIcon,
  RadarIcon,
  ScatterChartIcon,
  TableIcon,
  TargetIcon,
  WaypointsIcon,
} from "lucide-react";
import type { ChartKind } from "@/lib/dashboards";

export const CHART_ICONS: Record<ChartKind, LucideIcon> = {
  kpi: HashIcon,
  area: ActivityIcon,
  line: ChartLineIcon,
  column: ChartColumnIcon,
  bars: AlignLeftIcon,
  funnel: FilterIcon,
  donut: ChartPieIcon,
  rings: CircleDotIcon,
  radar: RadarIcon,
  scatter: ScatterChartIcon,
  sankey: WaypointsIcon,
  score: GaugeIcon,
  gauge: TargetIcon,
  treemap: LayoutGridIcon,
  heatmap: Grid3x3Icon,
  table: TableIcon,
};
