type IconModule = { svg: string };

const ICONS: Record<string, () => Promise<{ default: IconModule }>> = {
  "apache-cassandra": () => import("thesvg/apache-cassandra"),
  appwrite: () => import("thesvg/appwrite"),
  convex: () => import("thesvg/convex"),
  firebase: () => import("thesvg/firebase"),
  pocketbase: () => import("thesvg/pocketbase"),
  "apache-doris": () => import("thesvg/apache-doris"),
  "apache-hive": () => import("thesvg/apache-hive"),
  "aws-amazon-athena": () => import("thesvg/aws-amazon-athena"),
  "aws-amazon-simple-storage-service": () => import("thesvg/aws-amazon-simple-storage-service"),
  backblaze: () => import("thesvg/backblaze"),
  digitalocean: () => import("thesvg/digitalocean"),
  "google-cloud-storage": () => import("thesvg/google-cloud-storage"),
  minio: () => import("thesvg/minio"),
  "aws-amazon-documentdb": () => import("thesvg/aws-amazon-documentdb"),
  "aws-amazon-dynamodb": () => import("thesvg/aws-amazon-dynamodb"),
  "aws-amazon-redshift": () => import("thesvg/aws-amazon-redshift"),
  "azure-azure-cosmos-db": () => import("thesvg/azure-azure-cosmos-db"),
  clickhouse: () => import("thesvg/clickhouse"),
  cloudflare: () => import("thesvg/cloudflare"),
  "cockroach-labs": () => import("thesvg/cockroach-labs"),
  cratedb: () => import("thesvg/cratedb"),
  databricks: () => import("thesvg/databricks"),
  duckdb: () => import("thesvg/duckdb"),
  elasticsearch: () => import("thesvg/elasticsearch"),
  ferretdb: () => import("thesvg/ferretdb"),
  firebird: () => import("thesvg/firebird"),
  "google-bigquery": () => import("thesvg/google-bigquery"),
  ibm: () => import("thesvg/ibm"),
  influxdb: () => import("thesvg/influxdb"),
  mariadb: () => import("thesvg/mariadb"),
  "microsoft-access": () => import("thesvg/microsoft-access"),
  "microsoft-sql-server": () => import("thesvg/microsoft-sql-server"),
  mongodb: () => import("thesvg/mongodb"),
  mysql: () => import("thesvg/mysql"),
  neon: () => import("thesvg/neon"),
  opensearch: () => import("thesvg/opensearch"),
  oracle: () => import("thesvg/oracle"),
  planetscale: () => import("thesvg/planetscale"),
  postgresql: () => import("thesvg/postgresql"),
  redis: () => import("thesvg/redis"),
  sap: () => import("thesvg/sap"),
  scylladb: () => import("thesvg/scylladb"),
  singlestore: () => import("thesvg/singlestore"),
  snowflake: () => import("thesvg/snowflake"),
  sqlite: () => import("thesvg/sqlite"),
  supabase: () => import("thesvg/supabase"),
  teradata: () => import("thesvg/teradata"),
  tidb: () => import("thesvg/tidb"),
  timescale: () => import("thesvg/timescale"),
  trino: () => import("thesvg/trino"),
  turso: () => import("thesvg/turso"),
  valkey: () => import("thesvg/valkey"),
  vitess: () => import("thesvg/vitess"),
  yugabytedb: () => import("thesvg/yugabytedb"),
};

export async function thesvgSvgForSlug(slug: string | null | undefined): Promise<string | null> {
  if (!slug || !Object.hasOwn(ICONS, slug)) return null;
  return (await ICONS[slug]()).default.svg;
}
