import type { TourChapter } from "@/lib/tour/types";

export const TOUR_CHAPTERS: TourChapter[] = [
  {
    id: "welcome",
    title: "Willkommen",
    summary: "Kopfzeile, Suche und die wichtigsten Bereiche.",
    steps: [
      {
        id: "hello",
        title: "Willkommen bei l8db",
        body: "Das ist deine Desktop-Datenbankzentrale. Die Tour führt dich Kapitel für Kapitel durch Verbindungen, Explorer, Tabellen, SQL, Diagramme und Systemseiten. Links bleibt die Übersicht sichtbar — springe jederzeit, oder lass den Autopiloten klicken und navigieren.",
        route: "/",
        side: "over",
      },
      {
        id: "header-nav",
        title: "Bereiche oben links",
        body: "Das Logo bringt dich zur Übersicht. Daneben liegen SQL-Arbeitsplatz, ER-Diagramm, Über und Release Notes. Diese Icons bleiben überall erreichbar — unabhängig davon, welche Datenbank gerade offen ist.",
        target: "[data-tour='header-nav']",
        side: "bottom",
      },
      {
        id: "header-search",
        title: "Befehlssuche",
        body: "⌘K bzw. Ctrl+K öffnet die Palette. Dort wechselst du Verbindungen und springst direkt in Tabellen, ohne die Sidebar zu durchsuchen. Tippe den Verbindungsnamen oder den Tabellennamen.",
        target: "[data-tour='header-search']",
        side: "bottom",
      },
      {
        id: "header-actions",
        title: "Aktionen rechts",
        body: "Aktualisieren lädt Schema-Objekte neu. Der Verzweigungs-Button öffnet das Transaktionsprotokoll. Daneben liegen Theme, Treiberstatus und Einstellungen. Die Tour kannst du dort jederzeit von vorn starten.",
        target: "[data-tour='header-actions']",
        side: "bottom",
      },
    ],
  },
  {
    id: "connections",
    title: "Verbindungen",
    summary: "Engine wählen, speichern, verbinden.",
    steps: [
      {
        id: "connections-page",
        title: "Datenbank wählen",
        body: "Hier liegen alle gespeicherten Verbindungen als Karten. Eine neue Engine legst du über die Kachel „Neu“ an. Passwörter landen im System-Schlüsselbund, nicht in der Verbindungs-URL.",
        route: "/connections",
        target: "[data-tour='connections-page']",
        side: "bottom",
      },
      {
        id: "add-connection",
        title: "Neue Verbindung anlegen",
        body: "Klicke auf „Neu“. Die Tour wartet, bis der Editor offen ist. Im Autopilot wird der Klick für dich ausgeführt.",
        target: "[data-tour='connection-add']",
        autoClick: "[data-tour='connection-add']",
        wait: { type: "element", selector: "[data-tour='connection-editor']" },
        waitHint: "Warte auf den Editor…",
        skipIf: "editor-open",
        side: "left",
      },
      {
        id: "connection-editor",
        title: "Engine und Zugangsdaten",
        body: "Wähle zuerst die Engine (Postgres, MySQL, SQLite, …). Danach Host, Port, Datenbank, Benutzer und Passwort — oder eine komplette URL. Optional: SSH-Tunnel, TLS-Modus und ein Verbindungstest, bevor du speicherst.",
        target: "[data-tour='connection-editor']",
        side: "right",
      },
      {
        id: "save-connection",
        title: "Speichern — jetzt du",
        body: "Fülle die Felder aus und speichere die Verbindung (Slide-Button). Die Tour wartet, bis eine neue Verbindung im Speicher liegt. Du kannst diesen Schritt überspringen, wenn du später speichern willst.",
        target: "[data-tour='connection-save']",
        wait: { type: "connection-added" },
        waitHint: "Warte, bis die Verbindung gespeichert ist…",
        side: "top",
      },
    ],
  },
  {
    id: "workspace",
    title: "Arbeitsplatz",
    summary: "Dashboard nach dem Verbinden.",
    steps: [
      {
        id: "connect-now",
        title: "Verbindung aktivieren",
        body: "Ohne aktive Verbindung bleibt der Arbeitsplatz leer. Öffne eine gespeicherte Karte oder wähle sie in der Suche. Die Tour wartet, bis eine Verbindung aktiv ist.",
        route: "/",
        wait: { type: "active-connection" },
        waitHint: "Warte auf eine aktive Verbindung…",
        skipIf: "no-connection",
        side: "over",
      },
      {
        id: "dashboard",
        title: "Übersicht der aktiven Datenbank",
        body: "Hier siehst du Name, Engine, Datenbank und Schema. Die Kennzahlen zählen Tabellen, Views, Funktionen und mehr — abhängig davon, was die Engine kann.",
        route: "/",
        target: "[data-tour='dashboard']",
        skipIf: "no-connection",
        side: "bottom",
      },
      {
        id: "dashboard-actions",
        title: "Schnellstart vom Dashboard",
        body: "Aktualisieren lädt die Objektliste neu. „SQL-Abfrage“ öffnet einen neuen Editor-Tab. Die Tabellenliste darunter filtert lokal, ohne die Datenbank zu belasten.",
        target: "[data-tour='dashboard-actions']",
        skipIf: "no-connection",
        side: "left",
      },
    ],
  },
  {
    id: "explorer",
    title: "Explorer",
    summary: "Sidebar: Verbindung, Schema, Objekte.",
    steps: [
      {
        id: "sidebar-connection",
        title: "Verbindung wechseln",
        body: "Dieser Schalter sitzt dauerhaft links. Darüber wechselst du gespeicherte Verbindungen oder landest wieder in der Verwaltung. Ein Wechsel prüft den Tunnel und die Erreichbarkeit, bevor der Arbeitsplatz umschaltet.",
        route: "/",
        target: "[data-tour='sidebar-connection']",
        skipIf: "no-connection",
        side: "right",
      },
      {
        id: "sidebar-scope",
        title: "Datenbank und Schema",
        body: "Viele Server haben mehrere Datenbanken und Schemas. Die Auswahl gilt für Tabellen, Queries und das ER-Diagramm. Rechts am Schema liegt die Verwaltung (anlegen, löschen).",
        target: "[data-tour='sidebar-scope']",
        skipIf: "no-connection",
        side: "right",
      },
      {
        id: "sidebar-tabs",
        title: "Objektarten",
        body: "Tabs trennen Tabellen, Views, Funktionen, Packages, Extensions, Rollen und Sequenzen. Was die aktuelle Engine nicht kann, bleibt ausgeblendet — dieselbe Oberfläche, andere Fähigkeiten.",
        target: "[data-tour='sidebar-tabs']",
        skipIf: "no-connection",
        side: "right",
      },
      {
        id: "sidebar-search",
        title: "Objekte filtern",
        body: "Die Suche filtert die Liste nach Name oder Spalte. Rechts daneben öffnet die große Suche alle Tabellen der Verbindung. Klicke als Nächstes eine Tabelle an — oder lass den Autopiloten die erste nehmen.",
        target: "[data-tour='sidebar-search']",
        skipIf: "no-connection",
        side: "right",
      },
      {
        id: "open-table",
        title: "Tabelle öffnen",
        body: "Klicke eine Tabelle. Die Tour wartet, bis die Datenansicht offen ist. Im Autopilot wird die erste Tabelle für dich geöffnet.",
        target: "[data-tour='sidebar-table']",
        autoClick: "[data-tour='sidebar-table']",
        tableRoute: true,
        wait: { type: "route", includes: "/tables/" },
        waitHint: "Warte, bis eine Tabelle offen ist…",
        skipIf: "no-tables",
        side: "right",
      },
    ],
  },
  {
    id: "tables",
    title: "Tabellen",
    summary: "Daten, Filter, Spalten, Export.",
    steps: [
      {
        id: "table-toolbar",
        title: "Daten, Spalten, Extra-Tabs",
        body: "Oben wechselst du zwischen Daten, Spalten, Triggern, Indexes, RLS und Partitionen — je nach Engine. Export schreibt die aktuelle Seite als CSV oder JSON.",
        tableRoute: true,
        target: "[data-tour='table-toolbar']",
        skipIf: "no-connection",
        side: "bottom",
      },
      {
        id: "table-filter",
        title: "Filter und gespeicherte Sichten",
        body: "Der Filter baut WHERE-Bedingungen oder nimmt rohes SQL. Gespeicherte Sichten merken häufige Ausschnitte. Sortierung und Seitengröße kommen aus den Einstellungen (Zeilenlimit).",
        tableRoute: true,
        target: "[data-tour='table-filter']",
        skipIf: "no-connection",
        side: "bottom",
      },
      {
        id: "table-add",
        title: "Neue Zeile",
        body: "„Neue Zeile“ öffnet ein Formular anhand der Spaltentypen. Änderungen können sofort geschrieben oder — wenn aktiviert — erst im Transaktionspanel gesammelt werden.",
        tableRoute: true,
        target: "[data-tour='table-add']",
        skipIf: "no-connection",
        side: "left",
      },
    ],
  },
  {
    id: "sql",
    title: "SQL-Arbeitsplatz",
    summary: "Editor, Ausführen, Explain, Verlauf.",
    steps: [
      {
        id: "query-page",
        title: "Mehrere Query-Tabs",
        body: "Jeder Editor ist ein eigener Tab. Du kannst mehrere Entwürfe parallel halten, speichern und später wieder öffnen. Ohne Verbindung bleibt Ausführen deaktiviert.",
        route: "/query",
        target: "[data-tour='query-toolbar']",
        side: "bottom",
      },
      {
        id: "query-run",
        title: "Ausführen und Explain",
        body: "Ausführen schickt die Anweisung an die aktive Datenbank. Explain zeigt den Plan ohne Seiteneffekt, Explain Analyze misst die echte Ausführung. Ergebnisse exportierst du als CSV oder JSON.",
        target: "[data-tour='query-run']",
        side: "bottom",
      },
      {
        id: "query-history",
        title: "Verlauf und Speichern",
        body: "Gespeicherte Queries bleiben an der Verbindung hängen. Der Verlauf merkt ausgeführte Statements — nützlich, um eine spontane Analyse wiederzufinden.",
        target: "[data-tour='query-history']",
        side: "bottom",
      },
    ],
  },
  {
    id: "diagram",
    title: "ER-Diagramm",
    summary: "Beziehungen im aktuellen Schema.",
    steps: [
      {
        id: "er",
        title: "Schema als Graph",
        body: "Das Diagramm legt Tabellen und Fremdschlüssel des aktuellen Schemas. Zoomen, verschieben, exportieren als Bild oder PDF. Großschemata brauchen einen Moment zum Layouten.",
        route: "/er-diagram",
        target: "[data-tour='er-page']",
        side: "left",
      },
    ],
  },
  {
    id: "transactions",
    title: "Transaktionen",
    summary: "Sammeln, prüfen, committen.",
    steps: [
      {
        id: "tx-toggle",
        title: "Protokoll öffnen",
        body: "Jede Zeilenänderung und jedes DML kann in einer Transaktion landen, wenn die Einstellung aktiv ist. Der Button in der Kopfzeile öffnet das Protokoll — die Tour öffnet es jetzt.",
        route: "/",
        target: "[data-tour='header-tx']",
        autoClick: "[data-tour='header-tx']",
        openTx: true,
        side: "bottom",
      },
      {
        id: "tx-panel",
        title: "Commit oder Rollback",
        body: "Offene Änderungen siehst du als Diff. Commit schreibt sie, Rollback verwirft sie. Ohne Transaktionsmodus speichert l8db jede Änderung sofort — das stellst du in den Einstellungen um.",
        target: "[data-tour='tx-panel']",
        side: "left",
      },
    ],
  },
  {
    id: "system",
    title: "System",
    summary: "Treiber, Einstellungen, Erweiterungen.",
    steps: [
      {
        id: "drivers",
        title: "Treiberfamilien",
        body: "Jede Engine braucht ihren Treiber. Hier siehst du, was bereit ist, und installierst Fehlendes. Optional-Features wie DuckDB oder ODBC erscheinen erst, wenn sie im Build aktiv sind.",
        route: "/drivers",
        target: "[data-tour='drivers-page']",
        side: "bottom",
      },
      {
        id: "settings",
        title: "Einstellungen",
        body: "Theme, Zeilenlimit, Editor-Schrift, Query-Timeout, SSH-Host-Keys, Transaktionsmodus und Updates. Unten startest du diese Tour jederzeit von Kapitel 1 neu.",
        route: "/settings",
        target: "[data-tour='settings-page']",
        side: "bottom",
      },
      {
        id: "about",
        title: "Über l8db",
        body: "Technik-Stack, Features und Links. Release Notes daneben erklären, was sich in der aktuellen Version geändert hat.",
        route: "/about",
        target: "[data-tour='about-page']",
        side: "bottom",
      },
    ],
  },
];

export function flattenTour() {
  return TOUR_CHAPTERS.flatMap((chapter, chapterIndex) =>
    chapter.steps.map((step, stepIndex) => ({ chapter, chapterIndex, step, stepIndex })),
  );
}

export function tourProgress(chapterIndex: number, stepIndex: number) {
  const done = TOUR_CHAPTERS.slice(0, chapterIndex).reduce((sum, chapter) => sum + chapter.steps.length, 0);
  return {
    current: done + stepIndex + 1,
    total: flattenTour().length,
  };
}
