import { thesvgSvgForSlug } from "../provider-logo/icons";
import { candidateKeys } from "./name-keys";

type IconModule = { svg: string };

const BRAND_ICONS: Record<string, () => Promise<{ default: IconModule }>> = {
  anthropic: () => import("thesvg/anthropic"),
  auth0: () => import("thesvg/auth0"),
  clerk: () => import("thesvg/clerk"),
  datadog: () => import("thesvg/datadog"),
  discord: () => import("thesvg/discord"),
  docker: () => import("thesvg/docker"),
  elasticsearch: () => import("thesvg/elasticsearch"),
  figma: () => import("thesvg/figma"),
  firebase: () => import("thesvg/firebase"),
  github: () => import("thesvg/github"),
  gitlab: () => import("thesvg/gitlab"),
  "google-gemini": () => import("thesvg/google-gemini"),
  grafana: () => import("thesvg/grafana"),
  kafka: () => import("thesvg/kafka"),
  kubernetes: () => import("thesvg/kubernetes"),
  meilisearch: () => import("thesvg/meilisearch"),
  notion: () => import("thesvg/notion"),
  openai: () => import("thesvg/openai"),
  paypal: () => import("thesvg/paypal"),
  prisma: () => import("thesvg/prisma"),
  sentry: () => import("thesvg/sentry"),
  shopify: () => import("thesvg/shopify"),
  slack: () => import("thesvg/slack"),
  stripe: () => import("thesvg/stripe"),
  typesense: () => import("thesvg/typesense"),
  vercel: () => import("thesvg/vercel"),
};

const NAME_TO_BRAND: Record<string, string> = {
  openai: "openai",
  chatgpt: "openai",
  gpt: "openai",
  dalle: "openai",
  anthropic: "anthropic",
  claude: "anthropic",
  gemini: "google-gemini",
  googlegemini: "google-gemini",
  bard: "google-gemini",
  stripe: "stripe",
  github: "github",
  gitlab: "gitlab",
  shopify: "shopify",
  slack: "slack",
  discord: "discord",
  notion: "notion",
  figma: "figma",
  vercel: "vercel",
  firebase: "firebase",
  firestore: "firebase",
  prisma: "prisma",
  elastic: "elasticsearch",
  elasticsearch: "elasticsearch",
  meili: "meilisearch",
  meilisearch: "meilisearch",
  typesense: "typesense",
  kafka: "kafka",
  paypal: "paypal",
  auth0: "auth0",
  clerk: "clerk",
  sentry: "sentry",
  datadog: "datadog",
  grafana: "grafana",
  docker: "docker",
  kubernetes: "kubernetes",
  k8s: "kubernetes",
};

const NAME_TO_TECH: Record<string, string> = {
  pg: "postgresql",
  postgres: "postgresql",
  postgresql: "postgresql",
  postgis: "postgresql",
  mysql: "mysql",
  mariadb: "mariadb",
  mongo: "mongodb",
  mongodb: "mongodb",
  redis: "redis",
  valkey: "valkey",
  keydb: "redis",
  dragonfly: "redis",
  sqlite: "sqlite",
  duckdb: "duckdb",
  clickhouse: "clickhouse",
  snowflake: "snowflake",
  bigquery: "google-bigquery",
  databricks: "databricks",
  supabase: "supabase",
  neon: "neon",
  planetscale: "planetscale",
  turso: "turso",
  libsql: "turso",
  tidb: "tidb",
  timescale: "timescale",
  timescaledb: "timescale",
  cockroach: "cockroach-labs",
  cockroachdb: "cockroach-labs",
  yugabyte: "yugabytedb",
  yugabytedb: "yugabytedb",
  scylla: "scylladb",
  scylladb: "scylladb",
  cassandra: "apache-cassandra",
  oracle: "oracle",
  mssql: "microsoft-sql-server",
  sqlserver: "microsoft-sql-server",
  trino: "trino",
  vitess: "vitess",
  crate: "cratedb",
  cratedb: "cratedb",
  singlestore: "singlestore",
  teradata: "teradata",
  sap: "sap",
  hana: "sap",
  db2: "ibm",
  informix: "ibm",
  netezza: "ibm",
  doris: "apache-doris",
  hive: "apache-hive",
  athena: "aws-amazon-athena",
  redshift: "aws-amazon-redshift",
  ferretdb: "ferretdb",
  documentdb: "aws-amazon-documentdb",
  cosmosdb: "azure-azure-cosmos-db",
};

export async function brandSvgForName(name: string): Promise<string | null> {
  for (const key of candidateKeys(name)) {
    const slug = Object.hasOwn(NAME_TO_BRAND, key) ? NAME_TO_BRAND[key] : undefined;
    if (slug && Object.hasOwn(BRAND_ICONS, slug)) return (await BRAND_ICONS[slug]()).default.svg;
    const tech = Object.hasOwn(NAME_TO_TECH, key) ? NAME_TO_TECH[key] : undefined;
    if (tech) {
      const svg = await thesvgSvgForSlug(tech);
      if (svg) return svg;
    }
  }
  return null;
}
