import {
  Archive,
  Clock,
  CreditCard,
  Crown,
  Database,
  FileText,
  FlaskConical,
  Globe,
  HardDrive,
  Info,
  KeyRound,
  Lock,
  type LucideIcon,
  MapPin,
  Newspaper,
  Puzzle,
  Radio,
  Rocket,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Store,
  TrendingUp,
  Zap,
} from "lucide-react";

export const NAME_TO_SYSTEM: Record<string, LucideIcon> = {
  public: Globe,
  private: Lock,
  auth: KeyRound,
  users: KeyRound,
  user: KeyRound,
  account: KeyRound,
  accounts: KeyRound,
  login: KeyRound,
  identity: KeyRound,
  storage: HardDrive,
  files: HardDrive,
  file: HardDrive,
  uploads: HardDrive,
  upload: HardDrive,
  media: HardDrive,
  assets: HardDrive,
  attachments: HardDrive,
  blobs: HardDrive,
  blob: HardDrive,
  extensions: Puzzle,
  extension: Puzzle,
  ext: Puzzle,
  realtime: Radio,
  vault: ShieldCheck,
  pgcatalog: Database,
  informationschema: Info,
  sys: Settings,
  system: Settings,
  dbo: Settings,
  analytics: TrendingUp,
  bi: TrendingUp,
  report: TrendingUp,
  reports: TrendingUp,
  reporting: TrendingUp,
  metric: TrendingUp,
  metrics: TrendingUp,
  stat: TrendingUp,
  stats: TrendingUp,
  warehouse: TrendingUp,
  mart: TrendingUp,
  lake: TrendingUp,
  gold: TrendingUp,
  silver: TrendingUp,
  bronze: TrendingUp,
  logs: FileText,
  log: FileText,
  logging: FileText,
  audit: FileText,
  event: FileText,
  events: FileText,
  test: FlaskConical,
  tests: FlaskConical,
  testing: FlaskConical,
  demo: FlaskConical,
  sample: FlaskConical,
  sandbox: FlaskConical,
  dev: FlaskConical,
  development: FlaskConical,
  qa: FlaskConical,
  prod: Rocket,
  production: Rocket,
  live: Rocket,
  main: Rocket,
  master: Rocket,
  primary: Rocket,
  backup: Archive,
  backups: Archive,
  archive: Archive,
  cache: Zap,
  temp: Zap,
  tmp: Zap,
  queue: Clock,
  queues: Clock,
  job: Clock,
  jobs: Clock,
  task: Clock,
  tasks: Clock,
  worker: Clock,
  cron: Clock,
  schedule: Clock,
  search: Search,
  billing: CreditCard,
  payment: CreditCard,
  payments: CreditCard,
  invoice: CreditCard,
  invoices: CreditCard,
  subscription: CreditCard,
  subscriptions: CreditCard,
  shop: Store,
  store: Store,
  commerce: Store,
  product: Store,
  products: Store,
  order: Store,
  orders: Store,
  customer: Store,
  customers: Store,
  cart: Store,
  checkout: Store,
  cms: Newspaper,
  content: Newspaper,
  blog: Newspaper,
  post: Newspaper,
  posts: Newspaper,
  page: Newspaper,
  pages: Newspaper,
  article: Newspaper,
  articles: Newspaper,
  news: Newspaper,
  geo: MapPin,
  location: MapPin,
  locations: MapPin,
  place: MapPin,
  places: MapPin,
  map: MapPin,
  maps: MapPin,
  ai: Sparkles,
  ml: Sparkles,
  embedding: Sparkles,
  embeddings: Sparkles,
  vector: Sparkles,
  vectors: Sparkles,
  llm: Sparkles,
  agent: Sparkles,
  agents: Sparkles,
  bot: Sparkles,
  chat: Sparkles,
  config: Settings,
  configs: Settings,
  setting: Settings,
  settings: Settings,
  option: Settings,
  options: Settings,
  admin: Crown,
  administrator: Crown,
  root: Crown,
};
