export const BUILTIN_FUNCTIONS: { name: string; signature: string }[] = [
  { name: "COUNT", signature: "COUNT(expression)" },
  { name: "SUM", signature: "SUM(expression)" },
  { name: "AVG", signature: "AVG(expression)" },
  { name: "MIN", signature: "MIN(expression)" },
  { name: "MAX", signature: "MAX(expression)" },
  { name: "ARRAY_AGG", signature: "ARRAY_AGG(expression)" },
  { name: "STRING_AGG", signature: "STRING_AGG(expression, delimiter)" },
  { name: "LISTAGG", signature: "LISTAGG(expression, delimiter) WITHIN GROUP (ORDER BY ...)" },
  { name: "JSON_AGG", signature: "JSON_AGG(expression)" },
  { name: "JSONB_AGG", signature: "JSONB_AGG(expression)" },
  { name: "ROW_NUMBER", signature: "ROW_NUMBER()" },
  { name: "RANK", signature: "RANK()" },
  { name: "DENSE_RANK", signature: "DENSE_RANK()" },
  { name: "LAG", signature: "LAG(expression, offset, default)" },
  { name: "LEAD", signature: "LEAD(expression, offset, default)" },
  { name: "FIRST_VALUE", signature: "FIRST_VALUE(expression)" },
  { name: "LAST_VALUE", signature: "LAST_VALUE(expression)" },
  { name: "NTH_VALUE", signature: "NTH_VALUE(expression, n)" },
  { name: "NTILE", signature: "NTILE(n)" },
  { name: "PERCENT_RANK", signature: "PERCENT_RANK()" },
  { name: "CUME_DIST", signature: "CUME_DIST()" },
  { name: "LENGTH", signature: "LENGTH(string)" },
  { name: "LOWER", signature: "LOWER(string)" },
  { name: "UPPER", signature: "UPPER(string)" },
  { name: "TRIM", signature: "TRIM(string)" },
  { name: "LTRIM", signature: "LTRIM(string)" },
  { name: "RTRIM", signature: "RTRIM(string)" },
  { name: "CONCAT", signature: "CONCAT(val1, val2, ...)" },
  { name: "CONCAT_WS", signature: "CONCAT_WS(separator, val1, val2, ...)" },
  { name: "SUBSTRING", signature: "SUBSTRING(string FROM start FOR length)" },
  { name: "SUBSTR", signature: "SUBSTR(string, start, length)" },
  { name: "INSTR", signature: "INSTR(string, substring)" },
  { name: "REPLACE", signature: "REPLACE(string, from, to)" },
  { name: "REGEXP_REPLACE", signature: "REGEXP_REPLACE(string, pattern, replacement)" },
  { name: "REGEXP_MATCH", signature: "REGEXP_MATCH(string, pattern)" },
  { name: "SPLIT_PART", signature: "SPLIT_PART(string, delimiter, n)" },
  { name: "POSITION", signature: "POSITION(substring IN string)" },
  { name: "STRPOS", signature: "STRPOS(string, substring)" },
  { name: "INITCAP", signature: "INITCAP(string)" },
  { name: "REPEAT", signature: "REPEAT(string, n)" },
  { name: "REVERSE", signature: "REVERSE(string)" },
  { name: "LPAD", signature: "LPAD(string, length, fill)" },
  { name: "RPAD", signature: "RPAD(string, length, fill)" },
  { name: "FORMAT", signature: "FORMAT(format, ...)" },
  { name: "STARTS_WITH", signature: "STARTS_WITH(string, prefix)" },
  { name: "ABS", signature: "ABS(x)" },
  { name: "CEIL", signature: "CEIL(x)" },
  { name: "FLOOR", signature: "FLOOR(x)" },
  { name: "ROUND", signature: "ROUND(x, decimal_places)" },
  { name: "TRUNC", signature: "TRUNC(x, decimal_places)" },
  { name: "SIGN", signature: "SIGN(x)" },
  { name: "POWER", signature: "POWER(base, exponent)" },
  { name: "SQRT", signature: "SQRT(x)" },
  { name: "EXP", signature: "EXP(x)" },
  { name: "LN", signature: "LN(x)" },
  { name: "LOG", signature: "LOG(base, x)" },
  { name: "MOD", signature: "MOD(dividend, divisor)" },
  { name: "RANDOM", signature: "RANDOM()" },
  { name: "PI", signature: "PI()" },
  { name: "NOW", signature: "NOW()" },
  { name: "SYSDATE", signature: "SYSDATE" },
  { name: "SYSTIMESTAMP", signature: "SYSTIMESTAMP" },
  { name: "CURRENT_DATE", signature: "CURRENT_DATE" },
  { name: "CURRENT_TIME", signature: "CURRENT_TIME" },
  { name: "CURRENT_TIMESTAMP", signature: "CURRENT_TIMESTAMP" },
  { name: "DATE_PART", signature: "DATE_PART('field', source)" },
  { name: "DATE_TRUNC", signature: "DATE_TRUNC('field', source)" },
  { name: "EXTRACT", signature: "EXTRACT(field FROM source)" },
  { name: "AGE", signature: "AGE(timestamp1, timestamp2)" },
  { name: "ADD_MONTHS", signature: "ADD_MONTHS(date, n)" },
  { name: "TO_DATE", signature: "TO_DATE(string, format)" },
  { name: "TO_TIMESTAMP", signature: "TO_TIMESTAMP(string, format)" },
  { name: "TO_CHAR", signature: "TO_CHAR(value, format)" },
  { name: "TO_NUMBER", signature: "TO_NUMBER(string, format)" },
  { name: "MAKE_DATE", signature: "MAKE_DATE(year, month, day)" },
  { name: "CLOCK_TIMESTAMP", signature: "CLOCK_TIMESTAMP()" },
  { name: "TO_JSON", signature: "TO_JSON(value)" },
  { name: "TO_JSONB", signature: "TO_JSONB(value)" },
  { name: "JSON_BUILD_OBJECT", signature: "JSON_BUILD_OBJECT(key, value, ...)" },
  { name: "JSONB_BUILD_OBJECT", signature: "JSONB_BUILD_OBJECT(key, value, ...)" },
  { name: "JSON_BUILD_ARRAY", signature: "JSON_BUILD_ARRAY(...)" },
  { name: "JSONB_BUILD_ARRAY", signature: "JSONB_BUILD_ARRAY(...)" },
  { name: "JSON_OBJECT_KEYS", signature: "JSON_OBJECT_KEYS(json)" },
  { name: "JSONB_OBJECT_KEYS", signature: "JSONB_OBJECT_KEYS(jsonb)" },
  { name: "JSON_ARRAY_ELEMENTS", signature: "JSON_ARRAY_ELEMENTS(json)" },
  { name: "JSONB_ARRAY_ELEMENTS", signature: "JSONB_ARRAY_ELEMENTS(jsonb)" },
  { name: "JSON_EACH", signature: "JSON_EACH(json)" },
  { name: "JSONB_EACH", signature: "JSONB_EACH(jsonb)" },
  { name: "ROW_TO_JSON", signature: "ROW_TO_JSON(record)" },
  { name: "JSONB_PRETTY", signature: "JSONB_PRETTY(jsonb)" },
  { name: "JSONB_STRIP_NULLS", signature: "JSONB_STRIP_NULLS(jsonb)" },
  { name: "UNNEST", signature: "UNNEST(array)" },
  { name: "ARRAY_LENGTH", signature: "ARRAY_LENGTH(array, dimension)" },
  { name: "ARRAY_TO_STRING", signature: "ARRAY_TO_STRING(array, delimiter)" },
  { name: "STRING_TO_ARRAY", signature: "STRING_TO_ARRAY(string, delimiter)" },
  { name: "ARRAY_APPEND", signature: "ARRAY_APPEND(array, element)" },
  { name: "ARRAY_PREPEND", signature: "ARRAY_PREPEND(element, array)" },
  { name: "CAST", signature: "CAST(value AS type)" },
  { name: "COALESCE", signature: "COALESCE(val1, val2, ...)" },
  { name: "NVL", signature: "NVL(value, default)" },
  { name: "NVL2", signature: "NVL2(value, if_not_null, if_null)" },
  { name: "DECODE", signature: "DECODE(expression, search, result, ..., default)" },
  { name: "NULLIF", signature: "NULLIF(val1, val2)" },
  { name: "GREATEST", signature: "GREATEST(val1, val2, ...)" },
  { name: "LEAST", signature: "LEAST(val1, val2, ...)" },
  { name: "PG_TYPEOF", signature: "PG_TYPEOF(value)" },
  { name: "PG_SIZE_PRETTY", signature: "PG_SIZE_PRETTY(size)" },
  { name: "VERSION", signature: "VERSION()" },
  { name: "GEN_RANDOM_UUID", signature: "GEN_RANDOM_UUID()" },
];
