import type { HotkeyCommand } from "./types";

export const GENERAL_COMMANDS: HotkeyCommand[] = [
  {
    id: "palette.open",
    label: "Suche und Befehlspalette öffnen",
    description: "Command Palette für Verbindungen, Objekte und Aktionen",
    area: "Allgemein",
    defaultHotkey: "Mod+K",
    aliases: ["Mod+Shift+P"],
    origin: "VS Code",
    reference: "VS Code: Strg+Umschalt+P, Chrome:Adressleisten-Suche",
  },
  {
    id: "palette.quickOpen",
    label: "Schnell öffnen",
    description: "Direkt zu Tabellen, Views und Abfragen springen",
    area: "Allgemein",
    defaultHotkey: "Mod+P",
    origin: "VS Code",
    reference: "VS Code: Strg+P Quick Open",
  },
  {
    id: "shortcuts.open",
    label: "Tastenkürzelhilfe öffnen",
    description: "Übersicht aller Befehle und eigene Belegung",
    area: "Allgemein",
    defaultHotkey: "F1",
    aliases: ["Mod+."],
    origin: "VS Code",
    reference: "VS Code: F1 Befehlspalette/Hilfe",
  },
  {
    id: "settings.open",
    label: "Einstellungen öffnen",
    description: "App-Einstellungen inklusive Hotkey-Konfiguration",
    area: "Allgemein",
    defaultHotkey: "Mod+,",
    origin: "VS Code",
    reference: "VS Code: Strg+,",
  },
  {
    id: "sidebar.toggle",
    label: "Seitenleiste ein- oder ausblenden",
    description: "Explorer/Sidebar umschalten",
    area: "Allgemein",
    defaultHotkey: "Mod+B",
    origin: "VS Code",
    reference: "VS Code: Strg+B",
  },
  {
    id: "dialog.close",
    label: "Dialog oder Overlay schließen",
    description: "Schließt Palette, Dialoge und Suchfelder",
    area: "Allgemein",
    defaultHotkey: "Escape",
    ignoreInputs: false,
    origin: "l8db",
  },
  {
    id: "app.refresh",
    label: "Aktuelle Ansicht neu laden",
    description: "Lädt Objekte der aktiven Verbindung neu, im Query-Editor: Abfrage ausführen",
    area: "Allgemein",
    defaultHotkey: "F5",
    aliases: ["Mod+R"],
    requiresConnection: false,
    ignoreInputs: false,
    origin: "Chrome",
    reference: "Chrome: F5 / Strg+R Neuladen",
  },
  {
    id: "app.focusSearch",
    label: "Suche fokussieren",
    description: "Springt in die Kopf-Suche wie in die Adressleiste",
    area: "Allgemein",
    defaultHotkey: "Mod+L",
    origin: "Chrome",
    reference: "Chrome: Strg+L Adressleiste",
  },
];
