import type { HotkeyCommand } from "./types";

export const SQL_EDITOR_COMMANDS: HotkeyCommand[] = [
  {
    id: "query.cancel",
    label: "Laufende Abfrage abbrechen",
    description: "Fordert den Abbruch der laufenden Abfrage an",
    routeScope: "query",
    origin: "l8db",
    area: "SQL-Editor",
    defaultHotkey: "Mod+Shift+Backspace",
    requiresConnection: true,
  },
  {
    id: "query.run",
    routeScope: "query",
    label: "Abfrage ausführen",
    description: "Führt das Editor-SQL aus, F5 nur im Query-Kontext",
    area: "SQL-Editor",
    defaultHotkey: "Mod+Enter",
    aliases: ["F5"],
    requiresConnection: true,
    origin: "l8db",
    reference: "SSMS/DataGrip: F5 Ausführen",
  },
  {
    id: "query.runSelection",
    routeScope: "query",
    label: "Markierung ausführen",
    description: "Nur den selektierten SQL-Bereich ausführen",
    area: "SQL-Editor",
    defaultHotkey: "Mod+Shift+Enter",
    aliases: ["F9"],
    requiresConnection: true,
    origin: "l8db",
  },
  {
    id: "query.runStatement",
    routeScope: "query",
    label: "Anweisung unter dem Cursor ausführen",
    description: "Statement an der Cursorposition ausführen",
    area: "SQL-Editor",
    defaultHotkey: "Mod+Alt+Enter",
    requiresConnection: true,
    origin: "l8db",
  },
  {
    id: "query.check",
    routeScope: "query",
    label: "Abfrage prüfen (kompilieren)",
    description: "Prüft das Editor-SQL ohne etwas auszuführen",
    area: "SQL-Editor",
    defaultHotkey: "Mod+Shift+K",
    requiresConnection: true,
    origin: "l8db",
  },
  {
    id: "query.save",
    routeScope: "query",
    label: "Abfrage speichern",
    description: "Speichert den Editor-Inhalt",
    area: "SQL-Editor",
    defaultHotkey: "Mod+S",
    origin: "VS Code",
    reference: "VS Code: Strg+S",
  },
  {
    id: "query.saveAs",
    routeScope: "query",
    label: "Abfrage speichern unter",
    description: "Speichern-unter-Dialog für SQL-Dateien",
    area: "SQL-Editor",
    defaultHotkey: "Mod+Shift+S",
    origin: "VS Code",
    reference: "VS Code: Strg+Umschalt+S",
  },
  {
    id: "query.format",
    routeScope: "query",
    label: "SQL formatieren",
    description: "Formatiert das Editor-SQL",
    area: "SQL-Editor",
    defaultHotkey: "Alt+Shift+F",
    origin: "VS Code",
    reference: "VS Code: Umschalt+Alt+F",
  },
  {
    id: "query.openFile",
    label: "SQL-Datei öffnen",
    description: "Datei als neuen Query-Tab laden",
    area: "SQL-Editor",
    defaultHotkey: "Mod+O",
    origin: "VS Code",
    reference: "VS Code/Chrome: Strg+O Öffnen",
  },
  {
    id: "query.comment",
    routeScope: "query",
    label: "Zeile kommentieren",
    description: "Kommentar für Auswahl oder Zeile umschalten",
    area: "SQL-Editor",
    defaultHotkey: "Mod+/",
    origin: "VS Code",
    reference: "VS Code: Strg+/",
  },
  {
    id: "query.bookmark",
    routeScope: "query",
    label: "Lesezeichen umschalten",
    description: "Bookmark an der Cursorzeile setzen oder entfernen",
    area: "SQL-Editor",
    defaultHotkey: "Mod+Alt+B",
    origin: "l8db",
  },
  {
    id: "query.nextBookmark",
    routeScope: "query",
    label: "Nächstes Lesezeichen",
    description: "Springt zum nächsten Bookmark",
    area: "SQL-Editor",
    defaultHotkey: "F2",
    origin: "VS Code",
    reference: "VS Code: F2/F8 Navigation",
  },
  {
    id: "query.prevBookmark",
    routeScope: "query",
    label: "Vorheriges Lesezeichen",
    description: "Springt zum vorherigen Bookmark",
    area: "SQL-Editor",
    defaultHotkey: "Shift+F2",
    origin: "VS Code",
  },
  {
    id: "query.history",
    routeScope: "query",
    label: "Abfrageverlauf öffnen",
    description: "Zuletzt ausgeführte Statements",
    area: "SQL-Editor",
    defaultHotkey: "Mod+H",
    origin: "l8db",
  },
];
