import type { HotkeyCommand } from "./types";

export const GRID_COMMANDS: HotkeyCommand[] = [
  {
    id: "grid.search",
    routeScope: "data",
    label: "In Ergebnissen suchen",
    description: "Volltextsuche im Datengitter",
    area: "Datengitter",
    defaultHotkey: "Mod+F",
    requiresConnection: true,
    origin: "VS Code",
    reference: "VS Code/Chrome: Strg+F",
  },
  {
    id: "grid.copy",
    routeScope: "data",
    label: "Auswahl kopieren",
    description: "Selektierte Zellen in die Zwischenablage",
    area: "Datengitter",
    defaultHotkey: "Mod+C",
    requiresConnection: true,
    origin: "l8db",
  },
  {
    id: "grid.export",
    routeScope: "data",
    label: "Ergebnisse exportieren",
    description: "Exportdialog für das aktuelle Ergebnis",
    area: "Datengitter",
    defaultHotkey: "Mod+E",
    requiresConnection: true,
    origin: "l8db",
  },
  {
    id: "grid.nextPage",
    routeScope: "data",
    label: "Nächste Seite",
    description: "Blättert im Datengitter weiter",
    area: "Datengitter",
    defaultHotkey: "Alt+ArrowDown",
    requiresConnection: true,
    origin: "l8db",
  },
  {
    id: "grid.prevPage",
    routeScope: "data",
    label: "Vorherige Seite",
    description: "Blättert im Datengitter zurück",
    area: "Datengitter",
    defaultHotkey: "Alt+ArrowUp",
    requiresConnection: true,
    origin: "l8db",
  },
  {
    id: "settings.search",
    label: "Einstellungen durchsuchen",
    description: "Fokussiert die Einstellungssuche",
    area: "Allgemein",
    defaultHotkey: "Mod+Shift+F",
    origin: "l8db",
  },
];
