import type { HotkeyCommand } from "./types";

export const TAB_COMMANDS: HotkeyCommand[] = [
  {
    id: "tab.newQuery",
    label: "Neuen Abfrage-Tab öffnen",
    description: "Neuer Tab wie im Browser",
    area: "Tabs",
    defaultHotkey: "Mod+T",
    origin: "Chrome",
    reference: "Chrome: Strg+T Neuer Tab",
  },
  {
    id: "tab.close",
    label: "Aktiven Tab schließen",
    description: "Schließt den sichtbaren Arbeits-Tab",
    area: "Tabs",
    defaultHotkey: "Mod+W",
    origin: "Chrome",
    reference: "Chrome: Strg+W Tab schließen",
  },
  {
    id: "tab.reopen",
    label: "Geschlossenen Tab wieder öffnen",
    description: "Stellt den zuletzt geschlossenen Tab wieder her",
    area: "Tabs",
    defaultHotkey: "Mod+Shift+T",
    origin: "Chrome",
    reference: "Chrome: Strg+Umschalt+T",
  },
  {
    id: "tab.next",
    label: "Nächster Tab",
    description: "Wechselt zum Tab rechts",
    area: "Tabs",
    defaultHotkey: "Mod+PageDown",
    aliases: ["Control+Tab"],
    origin: "Chrome",
    reference: "Chrome: Strg+Tab",
  },
  {
    id: "tab.prev",
    label: "Vorheriger Tab",
    description: "Wechselt zum Tab links",
    area: "Tabs",
    defaultHotkey: "Mod+PageUp",
    aliases: ["Control+Shift+Tab"],
    origin: "Chrome",
    reference: "Chrome: Strg+Umschalt+Tab",
  },
  {
    id: "tab.jump1",
    label: "Zu Tab 1 springen",
    description: "Direktsprung wie im Browser",
    area: "Tabs",
    defaultHotkey: "Mod+1",
    origin: "Chrome",
    reference: "Chrome: Strg+1",
  },
  {
    id: "tab.jump2",
    label: "Zu Tab 2 springen",
    description: "Direktsprung wie im Browser",
    area: "Tabs",
    defaultHotkey: "Mod+2",
    origin: "Chrome",
    reference: "Chrome: Strg+2",
  },
  {
    id: "tab.jump3",
    label: "Zu Tab 3 springen",
    description: "Direktsprung wie im Browser",
    area: "Tabs",
    defaultHotkey: "Mod+3",
    origin: "Chrome",
    reference: "Chrome: Strg+3",
  },
  {
    id: "tab.jump4",
    label: "Zu Tab 4 springen",
    description: "Direktsprung wie im Browser",
    area: "Tabs",
    defaultHotkey: "Mod+4",
    origin: "Chrome",
    reference: "Chrome: Strg+4",
  },
  {
    id: "tab.jump5",
    label: "Zu Tab 5 springen",
    description: "Direktsprung wie im Browser",
    area: "Tabs",
    defaultHotkey: "Mod+5",
    origin: "Chrome",
    reference: "Chrome: Strg+5",
  },
  {
    id: "tab.jump6",
    label: "Zu Tab 6 springen",
    description: "Direktsprung wie im Browser",
    area: "Tabs",
    defaultHotkey: "Mod+6",
    origin: "Chrome",
    reference: "Chrome: Strg+6",
  },
  {
    id: "tab.jump7",
    label: "Zu Tab 7 springen",
    description: "Direktsprung wie im Browser",
    area: "Tabs",
    defaultHotkey: "Mod+7",
    origin: "Chrome",
    reference: "Chrome: Strg+7",
  },
  {
    id: "tab.jump8",
    label: "Zu Tab 8 springen",
    description: "Direktsprung wie im Browser",
    area: "Tabs",
    defaultHotkey: "Mod+8",
    origin: "Chrome",
    reference: "Chrome: Strg+8",
  },
  {
    id: "tab.last",
    label: "Zum letzten Tab springen",
    description: "Wie Strg+9 im Browser",
    area: "Tabs",
    defaultHotkey: "Mod+9",
    origin: "Chrome",
    reference: "Chrome: Strg+9",
  },
  {
    id: "view.split",
    label: "Ansicht teilen",
    description: "Aktiven Tab in Split-Ansicht öffnen",
    area: "Tabs",
    defaultHotkey: "Mod+\\",
    origin: "VS Code",
    reference: "VS Code: Editor teilen",
  },
];
