from pathlib import Path

root = Path(__file__).resolve().parent
previous = root.parent / 'ui-explorations-100'
source = (previous / 'build-gallery.mjs').read_text()
source = source.replace('Designrichtungen', 'Layoutkonzepte').replace('Designrichtung', 'Layoutkonzept')
source = source.replace('l8db-100-designs.zip', 'l8db-corporate-100-designs.zip')
source = source.replace('l8db.design-explorations.100', 'l8db.design-corporate.100')
source = source.replace('Design exploration · 2026', 'Corporate Design · 101–200')
source = source.replace('Die nächste Oberfläche', 'Im aktuellen l8db-Stil')
source = source.replace('Eine Datenbank.<br><span>100 Perspektiven.</span>', 'Vertrauter Stil.<br><span>100 neue Ideen.</span>')
source = source.replace('Von präzisen Arbeitsplätzen bis zu räumlichen Datenwelten: neue visuelle Sprachen und neue Wege, mit l8db zu arbeiten.', 'Neue Anordnungen für 20 Ansichten. Echte Aufnahmen des aktuellen l8db bilden die Stilreferenz; alle 30 Prinzipien von Laws of UX sind im Brief berücksichtigt.')
source = source.replace('<strong>10</strong><span>Ansichten</span>', '<strong>20</strong><span>Ansichten</span>')
source = source.replace('„Experimentell“ kennzeichnet bewusst neuartige Bedienkonzepte.', '<a href="ux-review.html">Corporate- und UX-Brief ansehen →</a>')
source = source.replace('<option>Produktnah</option><option>Experimentell</option>', '<option>Corporate Design</option>')
source = source.replace('<select id="level"', '<select hidden id="level"')
source = source.replace('color-scheme:dark;--bg:#0c0f14;--surface:#151921;--raised:#1b212c;--line:#2b3341;--text:#f0f3f7;--muted:#a0adbf;--accent:#c9ff70;--radius:16px;font-family:Inter', 'color-scheme:light;--bg:#f4f6f8;--surface:#ffffff;--raised:#e9edf1;--line:#d5dce2;--text:#202b35;--muted:#596775;--accent:#425d76;--radius:12px;font-family:"IBM Plex Sans"')
source = source.replace('color:#10170b', 'color:#fff').replace('color:#14200b', 'color:#fff')
source = source.replace('<span style="color:var(--accent)">.</span>', '')
source = source.replace('.wordmark{font-size:24px;font-weight:800;letter-spacing:-1.5px}', '.wordmark{font-size:22px;font-weight:650;letter-spacing:-1px}')
source = source.replace('font-size:clamp(34px,5.2vw,78px)', 'font-size:clamp(32px,4.6vw,64px)')
source = source.replace('<style>\n', '<style>\n@font-face{font-family:"IBM Plex Sans";src:url("references/ibm-plex-sans-latin.woff2") format("woff2");font-weight:100 900;font-display:swap}\n', 1)
source = source.replace('window.buildPreviewImages=async(start=0,end=designs.length)', 'window.buildPreviewImages=async(ids=designs.map(d=>d.id))')
source = source.replace('designs.slice(start,end)', 'designs.filter(d=>ids.includes(d.id))')
source = source.replace('AI-generierte Designkonzepte', 'AI-generierte Designkonzepte im aktuellen Corporate Design')
(root / 'build-gallery.mjs').write_text(source)

inline = (previous / 'build-inline.mjs').read_text()
inline = inline.replace('Designrichtungen', 'Layoutkonzepte').replace('Designrichtung', 'Layoutkonzept')
inline = inline.replace('100 Designbilder für l8db.', '100 weitere l8db-Entwürfe im aktuellen Corporate Design.')
inline = inline.replace('20 Layoutkonzepte, jeweils fünf Ansichten.', '20 Ansichten und 20 Layoutkonzepte · Hell und Dunkel · Entwürfe 101–200. Alle 30 Laws-of-UX-Prinzipien sind im Brief berücksichtigt.')
inline = inline.replace('l8db.design-explorations.inline', 'l8db.design-corporate.inline')
(root / 'build-inline.mjs').write_text(inline)

finalizer = (previous / 'finalize.py').read_text()
finalizer = finalizer.replace('[10] * 10', '[5] * 20')
finalizer = finalizer.replace("'viewCount': 10, 'imagesPerView': 10", "'viewCount': 20, 'imagesPerView': 5")
finalizer = finalizer.replace("'views': 10", "'views': 20")
finalizer = finalizer.replace('l8db-100-designs', 'l8db-corporate-100-designs')
finalizer = finalizer.replace("'pngIntegrity': 'passed'", "'pngIntegrity': 'passed', 'uxPrinciplesConsidered': 30, 'uxReview': 'Design criteria only; interaction and accessibility need implementation testing'")
(root / 'finalize.py').write_text(finalizer)
server = (previous / 'serve.mjs').read_text().replace('|| 4318', '|| 4319')
(root / 'serve.mjs').write_text(server)
print('Gallery, inline gallery, server and finalizer prepared')
