import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root=dirname(fileURLToPath(import.meta.url));
const ux=JSON.parse(readFileSync(join(root,'ux-principles.json'),'utf8'));
const manifest=JSON.parse(readFileSync(join(root,'manifest.json'),'utf8'));
const esc=x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const html=`<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>l8db · Corporate- und UX-Brief</title><style>
@font-face{font-family:"IBM Plex Sans";src:url("references/ibm-plex-sans-latin.woff2") format("woff2");font-weight:100 900;font-display:swap}
*{box-sizing:border-box}body{margin:0;font-family:"IBM Plex Sans",system-ui,sans-serif;background:#f4f6f8;color:#202b35;line-height:1.6}main{max-width:1200px;margin:auto;padding:32px 24px 64px}a{color:#425d76}a:focus-visible{outline:2px solid #425d76;outline-offset:4px}h1{font-size:38px;line-height:1.15;letter-spacing:-1px;margin:24px 0 18px}h2{font-size:22px;margin:36px 0 14px}p{max-width:900px;color:#596775}.intro{font-size:17px}.references{display:grid;grid-template-columns:1fr 1fr;gap:16px}figure{margin:0}figure img{display:block;width:100%;border:1px solid #d5dce2;border-radius:12px}figcaption{font-size:13px;color:#596775;margin-top:8px}.table{overflow:auto;border:1px solid #d5dce2;border-radius:12px;background:#fff}table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:13px 16px;text-align:left;border-bottom:1px solid #e5e9ed;vertical-align:top}th{background:#e9edf1;font-weight:600}td:first-child{width:230px}td:last-child{width:190px;color:#596775}tr:last-child td{border-bottom:0}.tokens{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.token{padding:16px;background:#fff;border:1px solid #d5dce2;border-radius:12px;font-size:13px}.token strong{display:block;margin-bottom:6px}.token code{font-size:11px}.scope{padding:18px;background:#e9edf1;border-radius:12px}.scope p{margin:0}.views{columns:2;column-gap:32px;font-size:14px}.views p{break-inside:avoid;margin:0 0 12px}.views strong{display:block;color:#202b35}@media(max-width:650px){.references,.tokens{grid-template-columns:1fr}.views{columns:1}h1{font-size:30px}main{padding:24px 16px 48px}}
</style></head><body><main><a href="index.html">← Zur Sammlung</a><h1>Corporate- und UX-Brief</h1><p class="intro">100 neue Entwürfe für 20 l8db-Ansichten. Die visuelle Identität stammt aus dem laufenden Produkt. Innovation entsteht durch Kontext, Anordnung und den Weg von der Aufgabe zum überprüfbaren Ergebnis.</p>
<h2>Aktueller Stil als feste Referenz</h2><div class="references"><figure><img src="references/l8db-current-light.png" alt="Aktuelles l8db im hellen Modus mit Beispieldaten"><figcaption>Reales l8db · Hell · synthetische Beispieldaten</figcaption></figure><figure><img src="references/l8db-current-dark.png" alt="Aktuelles l8db im dunklen Modus mit Beispieldaten"><figcaption>Reales l8db · Dunkel · synthetische Beispieldaten</figcaption></figure></div>
<p>Aufnahmen am 8. Oktober 2026 aus dem lokalen Vite-Frontend. Die Tauri-Antworten wurden ausschließlich im isolierten Browser für Beispieldaten simuliert. Produktcode und echte Datenbankverbindungen wurden dafür nicht geändert. Jede Generierung verwendet die passende Aufnahme als Stilreferenz.</p>
<div class="tokens"><div class="token"><strong>Typografie</strong>IBM Plex Sans für die Oberfläche; Monospace für SQL und technische Werte.</div><div class="token"><strong>Farben</strong>Kühle neutrale Flächen, gedämpftes Stahlblau, semantische Statusfarben mit Text und Symbol.</div><div class="token"><strong>Komponenten</strong>Feine Konturen, ruhige Schatten, kleine gerundete Rechtecke, 12px Panelradius und dünne Outline-Icons.</div><div class="token"><strong>Light-Basis</strong><code>background: oklch(0.975 0.004 248)<br>primary: oklch(0.4 0.045 248)</code></div><div class="token"><strong>Dark-Basis</strong><code>background: oklch(0.175 0.02 248)<br>primary: oklch(0.78 0.065 248)</code></div><div class="token"><strong>Wiedererkennbare Struktur</strong>Kompakter Header, Such-Pill, 56px Feature-Leiste, Objektbaum, Tabs und lesbare Datentabellen.</div></div>
<p>Quellen der Designbasis: <code>src/index.css</code>, <code>src/lib/db-theme.ts</code>, <code>src/lib/appearance.ts</code> und die Shell-Komponenten. Die tatsächliche Akzent-Chroma wird in <code>themeCssVars()</code> begrenzt. Die abweichenden visuellen Experimente der ersten Sammlung dienen hier nicht als Markenreferenz.</p>
<h2>Alle 30 Prinzipien berücksichtigt</h2><p>Die Sammlung <a href="https://lawsofux.com/" target="_blank" rel="noopener">Laws of UX</a> wurde am 8. Oktober 2026 gelesen. Die folgenden eigenen Kriterien übersetzen jedes Prinzip in den l8db-Kontext. Alle Kriterien sind im gemeinsamen Generierungsprompt enthalten; jede Ansicht nennt zusätzlich ihre besonders relevanten Prinzipien.</p>
<div class="table"><table><thead><tr><th>Prinzip und Quelle</th><th>Kriterium für l8db</th><th>Prüfebene</th></tr></thead><tbody>${ux.principles.map(p=>'<tr><td><a href="'+p.source+'" target="_blank" rel="noopener">'+esc(p.name)+'</a></td><td>'+esc(p.criterion)+'</td><td>'+esc(p.scope)+'</td></tr>').join('')}</tbody></table></div>
<h2>Schwerpunkte je Ansicht</h2><div class="views">${manifest.views.map(v=>'<p><strong>'+esc(v.name)+'</strong>'+v.lawIds.map(id=>esc(ux.principles.find(p=>p.slug===id).name)).join(' · ')+'</p>').join('')}</div>
<h2>Was die Bilder prüfen lassen</h2><div class="scope"><p>Visuell beurteilbar sind Hierarchie, Gruppierung, Wiedererkennbarkeit, Auswahl, Statusdarstellung und die Nähe von Kontext und Aktion. Die Rasterbilder zeigen Designabsichten; sie belegen keine funktionierenden Interaktionen, gemessene Feedbackzeiten, Tastaturbedienung oder vollständige Barrierefreiheit. Vor einer Umsetzung müssen Targetgrößen, Kontrast, Fokus, Screenreader, Fehlerbehandlung und Reaktionszeiten am echten Interface geprüft werden. Psychologische Effekte und Nutzungsprioritäten benötigen Nutzertests beziehungsweise Nutzungsdaten.</p></div>
<p>Die Bilder sind einzeln mit dem integrierten Bildgenerator erzeugt. Schrift, Werte und SQL können in Rasterkonzepten variieren. Verbindliche Beschriftungen und Verhalten stehen im exakten Prompt und in diesem Brief. <a href="manifest.json" download>Prompts und Bildkatalog herunterladen</a> · <a href="ux-principles.json" download>UX-Kriterien als JSON</a> · <a href="review-notes.json" download>Sichtprüfungen und konkrete Grenzen</a></p></main></body></html>`;
writeFileSync(join(root,'ux-review.html'),html);
console.log(JSON.stringify({file:join(root,'ux-review.html'),principles:ux.principles.length,views:manifest.views.length}));
