import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const manifest = JSON.parse(readFileSync(join(root, 'manifest.json'), 'utf8'));
const designs = manifest.images.map(({ id, style, styleSlug, tone, level, idea, view, viewSlug }) => ({ id, style, styleSlug, tone, level, idea, view, viewSlug, preview: join(root, 'thumbnails', id + '.jpg') })).sort((a, b) => ((Number(a.id) - 1) % 5 - (Number(b.id) - 1) % 5) || Number(a.id) - Number(b.id));
const html = `<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
*{box-sizing:border-box}body{margin:0;color:var(--foreground);font-family:var(--font-sans,system-ui);background:transparent}button,select,input{font:inherit}button{cursor:pointer}button:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid var(--ring);outline-offset:3px}.intro{margin:0 0 16px;color:var(--muted-foreground);font-size:13px;line-height:1.6}.intro strong{color:var(--foreground)}.filters{display:flex;flex-wrap:wrap;gap:8px;padding:0 0 16px}.filters input{width:100%;padding:10px 12px;border:1px solid var(--border);border-radius:var(--radius,10px);background:var(--card);color:var(--foreground)}.filters select,.filters button{flex:1;min-width:120px;border:1px solid var(--border);border-radius:var(--radius,10px);padding:9px;background:var(--card);color:var(--foreground);font-size:11px}.count{font-size:11px;color:var(--muted-foreground);margin:0 0 12px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px 12px}.card{min-width:0}.image{display:block;border:1px solid var(--border);padding:0;width:100%;border-radius:var(--radius,10px);overflow:hidden;background:var(--card);aspect-ratio:1.6}.image img{display:block;width:100%;height:100%;object-fit:cover}.title{display:flex;justify-content:space-between;gap:6px;align-items:start;margin:9px 0 4px;font-size:11px;font-weight:600}.view{font-size:10px;color:var(--muted-foreground);margin:0;line-height:1.5}.fav{border:0;background:transparent;color:var(--muted-foreground);cursor:pointer;padding:0 3px;font-size:14px}.fav[aria-pressed=true]{color:var(--accent-foreground)}.idea{font-size:10px;color:var(--muted-foreground);line-height:1.6;margin:6px 0 0}.badge{font-size:9px;color:var(--muted-foreground);margin:5px 0 0}.empty{grid-column:1/-1;padding:30px;text-align:center;font-size:12px;color:var(--muted-foreground)}dialog{padding:16px;border:1px solid var(--border);border-radius:var(--radius,12px);width:calc(100% - 24px);max-height:95vh;background:var(--popover);color:var(--foreground)}dialog::backdrop{background:#000b}.dialog-header{display:flex;align-items:center;justify-content:space-between;gap:12px;font-size:12px;margin:0 0 12px}.dialog-header button,.nav button{border:1px solid var(--border);border-radius:var(--radius,8px);padding:7px 10px;background:var(--card);color:var(--foreground);font-size:11px}.large{display:block;width:100%;height:auto;border-radius:var(--radius,8px)}.description{font-size:11px;line-height:1.6;color:var(--muted-foreground)}.nav{display:flex;justify-content:space-between;align-items:center;gap:12px;font-size:10px;color:var(--muted-foreground)}@media(max-width:480px){.grid{grid-template-columns:1fr}.title{font-size:12px}.view,.idea{font-size:11px}.filters select,.filters button{min-width:100px}}
</style></head><body>
<p class="intro"><strong>100 weitere l8db-Entwürfe im aktuellen Corporate Design.</strong> 20 Ansichten und 20 Layoutkonzepte · Hell und Dunkel · Entwürfe 101–200. Alle 30 Laws-of-UX-Prinzipien sind im Brief berücksichtigt. Bilder anklicken, nach Ansicht filtern oder Favoriten mit ★ markieren.</p>
<div class="filters"><input id="q" type="search" aria-label="Designs suchen" placeholder="Nummer, Design oder Idee suchen …"><select id="style" aria-label="Layoutkonzept"><option value="">Alle Layoutkonzepte</option>${manifest.styles.map(s => '<option value="' + s.slug + '">' + s.name + '</option>').join('')}</select><select id="view" aria-label="Ansicht"><option value="">Alle Ansichten</option>${manifest.views.map(v => '<option value="' + v.slug + '">' + v.name + '</option>').join('')}</select><select id="tone" aria-label="Helligkeit"><option value="">Hell & dunkel</option><option>Hell</option><option>Dunkel</option></select><button id="only-favorites" aria-pressed="false">★ Favoriten</button></div>
<p class="count" id="count" aria-live="polite"></p><div class="grid" id="grid"></div>
<dialog id="viewer" aria-label="Designvorschau"><div class="dialog-header"><strong id="title"></strong><button id="close" aria-label="Schließen">×</button></div><img id="large" class="large" alt=""><p id="description" class="description"></p><div class="nav"><button id="prev">← Vorheriger</button><span id="position"></span><button id="next">Nächster →</button></div></dialog>
<script>
const designs=${JSON.stringify(designs)};
const el=id=>document.getElementById(id);const state={q:'',style:'',view:'',tone:'',favorites:false,active:null};let saved=new Set();try{saved=new Set(JSON.parse(localStorage.getItem('l8db.design-corporate.inline')||'[]'));}catch{}
const esc=x=>x.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const visible=()=>designs.filter(d=>(!state.style||state.style===d.styleSlug)&&(!state.view||state.view===d.viewSlug)&&(!state.tone||state.tone===d.tone)&&(!state.favorites||saved.has(d.id))&&(!state.q||(d.id+' '+d.style+' '+d.view+' '+d.idea).toLowerCase().includes(state.q)));
function render(){const items=visible();el('count').textContent=items.length+' von 100 Entwürfen · Vorschauen; Originale im ZIP';el('grid').innerHTML=items.map(d=>'<article class="card"><button class="image" data-open="'+d.id+'" aria-label="Entwurf '+d.id+' öffnen"><img src="'+d.preview+'" alt="'+esc(d.style)+' – '+esc(d.view)+'" loading="lazy"></button><div class="title"><span>'+d.id+' · '+esc(d.style)+'</span><button class="fav" data-fav="'+d.id+'" aria-label="Entwurf '+d.id+' merken" aria-pressed="'+saved.has(d.id)+'">★</button></div><p class="view">'+esc(d.view)+'</p><p class="idea">'+esc(d.idea)+'</p><p class="badge">'+d.tone+' · '+d.level+'</p></article>').join('')||'<p class="empty">Keine passenden Entwürfe.</p>';el('only-favorites').setAttribute('aria-pressed',state.favorites);}
function openDesign(id){const d=designs.find(d=>d.id===id);if(!d)return;state.active=id;el('title').textContent=id+' · '+d.style+' · '+d.view;el('large').src=d.preview;el('large').alt=d.style+' – '+d.view;el('description').textContent=d.idea;el('position').textContent=visible().findIndex(d=>d.id===id)+1+' / '+visible().length;if(!el('viewer').open)el('viewer').showModal();}
function step(delta){const items=visible();const index=items.findIndex(d=>d.id===state.active);if(items.length)openDesign(items[(index+delta+items.length)%items.length].id);}
el('q').oninput=e=>{state.q=e.target.value.trim().toLowerCase();render();};['style','view','tone'].forEach(k=>el(k).onchange=e=>{state[k]=e.target.value;render();});el('only-favorites').onclick=()=>{state.favorites=!state.favorites;render();};el('grid').onclick=e=>{const open=e.target.closest('[data-open]');const favorite=e.target.closest('[data-fav]');if(open)openDesign(open.dataset.open);if(favorite){const id=favorite.dataset.fav;if(saved.has(id))saved.delete(id);else saved.add(id);try{localStorage.setItem('l8db.design-corporate.inline',JSON.stringify([...saved]));}catch{}render();}};el('close').onclick=()=>el('viewer').close();el('prev').onclick=()=>step(-1);el('next').onclick=()=>step(1);document.addEventListener('keydown',e=>{if(el('viewer').open&&e.key==='ArrowLeft')step(-1);if(el('viewer').open&&e.key==='ArrowRight')step(1);});render();console.log(JSON.stringify({designs:designs.length,styles:new Set(designs.map(d=>d.style)).size,views:new Set(designs.map(d=>d.view)).size,cards:document.querySelectorAll('.card').length}));
</script></body></html>`;
writeFileSync(join(root, 'inline-gallery.local'), html);
console.log(JSON.stringify({ file: join(root, 'inline-gallery.local'), images: designs.length }));
