import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const laws = [
  ['Aesthetic-Usability Effect','aesthetic-usability-effect','Ruhige, konsistente Oberflächen; Schönheit ersetzt keine klare Bedienung.','Consistent, restrained visual polish; never sacrifice legibility.','Visuell'],
  ['Choice Overload','choice-overload','Werkzeuge nach Aufgabe bündeln; seltene Optionen in Mehr, Hauptaufgaben sichtbar.','Group choices by task; show essentials and reveal advanced options.','Visuell und interaktiv'],
  ['Chunking','chunking','Semantische Gruppen für Verbindung, Objekt, Aufgabe und Ergebnis.','Use meaningful chunks for connection, object, task and result.','Visuell'],
  ['Cognitive Bias','cognitive-bias','Neutrale Beschriftungen, nachvollziehbare Zahlen, keine irreführenden Voreinstellungen.','Use neutral labels, contextual evidence and honest defaults.','Visuell und interaktiv'],
  ['Cognitive Load','cognitive-load','Eine dominante Aufgabe; aktives Objekt, Kontext und nächster Schritt erkennbar.','One dominant task with visible context and a clear next action.','Visuell'],
  ['Doherty Threshold','doherty-threshold','Laufstatus, Abbrechen und Fortschritt vorsehen; Feedbacklatenz muss später gemessen werden.','Show running, cancel and progress states when applicable; latency is an implementation requirement.','Interaktiv; im Bild nur Zustandskonzept'],
  ["Fitts’s Law",'fittss-law','Wichtige Ziele ausreichend groß, voneinander getrennt und nahe der Aufgabe platzieren.','Use generous separated targets for important controls close to the task.','Visuell und interaktiv'],
  ['Flow','flow','Arbeitskontext erhalten; störende Modals durch passende Inline-Hilfen ersetzen.','Preserve working context and avoid unnecessary interruption.','Visuell und interaktiv'],
  ['Goal-Gradient Effect','goal-gradient-effect','Bei mehrstufigen Aufgaben reale Schritte und verbleibende Arbeit zeigen.','Use truthful completed and remaining steps for multi-step tasks.','Visuell und interaktiv'],
  ["Hick’s Law",'hicks-law','Aktionen priorisieren und Entscheidungen in verständliche Schritte gliedern.','Prioritize actions and divide difficult decisions into clear steps.','Visuell'],
  ["Jakob’s Law",'jakobs-law','Bekannte Desktopmuster, Tabs, Objektbaum und bestehende l8db-Navigation beibehalten.','Keep familiar desktop conventions, tabs, object tree and l8db navigation.','Visuell'],
  ['Law of Common Region','law-of-common-region','Zusammengehörige Inhalte in klar abgegrenzten Bereichen.','Enclose related information in clear shared regions.','Visuell'],
  ['Law of Proximity','law-of-proximity','Beschriftung, Wert und Aktion räumlich zusammenhalten.','Keep related labels, values and actions close.','Visuell'],
  ['Law of Prägnanz','law-of-pragnanz','Einfache Formen und klare Hierarchie statt dekorativer Komplexität.','Use simple forms and an immediately readable hierarchy.','Visuell'],
  ['Law of Similarity','law-of-similarity','Gleiche Funktion erhält gleiche Form, Typografie und Zustandsdarstellung.','Give equivalent functions consistent styling and states.','Visuell'],
  ['Law of Uniform Connectedness','law-of-uniform-connectedness','Beziehungen durch beschriftete Linien oder eindeutige Zuordnung zeigen.','Show actual relationships with clear labeled connectors or alignment.','Visuell'],
  ['Mental Model','mental-model','Verbindung → Datenbank → Schema → Objekt bildet die sichtbare Struktur.','Follow connection, database, schema, object mental models.','Visuell und interaktiv'],
  ["Miller’s Law",'millers-law','Information sinnvoll gruppieren; keine starre Sieben-Elemente-Grenze anwenden.','Chunk meaningfully; do not enforce a magical seven-item limit.','Visuell'],
  ["Occam’s Razor",'occams-razor','Nur Elemente zeigen, die Verständnis oder Ausführung unterstützen.','Remove redundant decorative or functional elements.','Visuell'],
  ['Paradox of the Active User','paradox-of-the-active-user','Direkten Einstieg, Beispiele und Hilfe im Arbeitskontext anbieten.','Enable immediate action with examples and contextual help.','Visuell und interaktiv'],
  ['Pareto Principle','pareto-principle','Häufige Aufgaben prominent; Priorisierung später anhand Nutzung prüfen.','Put likely frequent actions first; verify priorities with usage research.','Visuell und empirisch'],
  ["Parkinson’s Law",'parkinsons-law','Aufgaben begrenzen und sinnvolle Startwerte anbieten, ohne künstlichen Zeitdruck.','Scope tasks and offer useful defaults without artificial pressure.','Interaktiv'],
  ['Peak-End Rule','peak-end-rule','Abschluss mit Ergebnis, Zusammenfassung und sinnvoller Folgeaktion.','Finish workflows with a clear outcome and useful next action.','Visuell und interaktiv'],
  ["Postel’s Law",'postels-law','Flexible Eingaben mit expliziter Validierung; technische Ausgabe präzise.','Accept practical input formats, validate explicitly and output precisely.','Interaktiv; im Bild nur Eingabekonzept'],
  ['Selective Attention','selective-attention','Auswahl und relevante Warnung hervorheben; Hintergrundwerkzeuge zurücknehmen.','Emphasize the selected item and relevant warning, quiet secondary tools.','Visuell'],
  ['Serial Position Effect','serial-position-effect','Primäre Schritte am Anfang, Ergebnis und nächste Aktion am Ende.','Place primary steps first and outcomes or next actions last.','Visuell'],
  ["Tesler’s Law",'teslers-law','System übernimmt Routine, notwendige Komplexität bleibt erreichbar.','Move routine work to the system without hiding necessary complexity.','Visuell und interaktiv'],
  ['Von Restorff Effect','von-restorff-effect','Eine klare Hauptaktion; Warnfarbe nur für echte Warnungen mit Text und Symbol.','One clear primary action; semantic color paired with text and icons.','Visuell'],
  ['Working Memory','working-memory','Vergleichswerte, Filter, Entwürfe und Kontext sichtbar erhalten.','Keep filters, drafts and comparison values visible rather than recalled.','Visuell und interaktiv'],
  ['Zeigarnik Effect','zeigarnik-effect','Echte offene Entwürfe und unerledigte Schritte kenntlich machen.','Mark actual unfinished drafts and tasks with truthful status.','Visuell und interaktiv'],
].map(([name,slug,criterion,prompt,scope]) => ({ name, slug, source:'https://lawsofux.com/'+slug+'/', criterion, prompt, scope }));

const layouts = [
  ['context-inspector','Kontextinspektor','Breite Hauptfläche mit einem schmalen, auf die Auswahl reagierenden rechten Inspektor.','A wide working surface and a slim right selection inspector; keep the conventional left object tree.'],
  ['priority-lanes','Prioritätsbahnen','Die wichtigste Aufgabe erhält ein breites Arbeitsband; Diagnose und Details liegen darunter.','A dominant upper work lane, a compact subordinate evidence lane below, one stable context rail.'],
  ['guided-context','Geführter Kontext','Ein kompakter Ablaufstreifen führt durch Aufgaben, während Daten und Kontext sichtbar bleiben.','A thin meaningful workflow strip above the main task, compact context sidebar and inline detail panels.'],
  ['master-detail','Master und Detail','Objektliste links, präzise Detailfläche rechts und eine gemeinsame Aktionsleiste.','A compact searchable master list, dominant detail surface, shared contextual action toolbar.'],
  ['linked-workbench','Verknüpfte Werkbank','Auswahl, Arbeitsfläche und Belege bleiben durch klare Zuordnung verbunden.','Three aligned panes for objects, primary work and evidence, clearly keyed selections and subtle relationship connectors.'],
  ['signal-and-evidence','Signal und Beleg','Eine wichtige Kennzahl steht über dem zugehörigen Verlauf und den überprüfbaren Details.','An evidence-led layout: compact summary, large primary analysis surface, lower trace or detail drawer.'],
  ['paired-surfaces','Gepaarte Flächen','Zwei synchronisierte Arbeitsbereiche erleichtern Vergleiche ohne Kontextwechsel.','Two aligned primary subpanes inside the existing app shell, a shared filter/context bar and compact footer review.'],
  ['task-continuity','Aufgabenkontinuität','Entwurf, Fortschritt und Ergebnis bilden einen nachvollziehbaren Arbeitsfluss.','A focused task canvas, persistent compact draft/progress strip, adjacent preview or summary with clear stage order.'],
  ['focused-canvas','Fokussierte Arbeitsfläche','Das aktive Objekt bekommt maximalen Platz; Hilfen bleiben in einem schmalen Seitenbereich.','Expand the dominant work canvas while retaining the 56px navigation rail and compact contextual object outline; quiet side detail drawer.'],
  ['context-ribbon','Kontextband','Verbindung und aktive Filter stehen in einem ruhigen Kontextband über den Daten.','Use a precise horizontal context ribbon above the working surface with a slim object list and a useful bottom result strip.'],
  ['decision-preview','Entscheidung mit Vorschau','Vor einer Änderung sind Wirkung, betroffene Objekte und Rückweg sichtbar.','A large preview, compact decision panel on the right, clear change evidence below and a single primary action.'],
  ['exploration-columns','Explorationsspalten','Zusammengehörige Informationen lassen sich in stabilen, beschrifteten Spalten untersuchen.','Stable semantic columns for navigation, central exploration and selected-object details; one coherent task hierarchy.'],
  ['progressive-details','Gestufte Details','Grundlegende Werkzeuge bleiben sichtbar; zusätzliche Details öffnen sich im gleichen Kontext.','Visible essential controls, a dominant work pane, expanded in-context advanced section with clear labels and compact supporting metadata.'],
  ['object-lens','Objektlinse','Das ausgewählte Objekt verbindet Daten, Struktur und relevante Folgeaktionen.','A selected-object lens integrated at the edge of the primary surface, subtle keyed row selection and nearby contextual actions.'],
  ['review-shelf','Prüfbereich','Eine untere Prüfzone sammelt Änderungen, Belege und den nächsten kontrollierten Schritt.','A broad primary work area, a shallow bottom review shelf, stable object sidebar and precisely grouped toolbar.'],
  ['workflow-bridge','Workflow-Brücke','Vorbereitung und Ergebnis stehen nebeneinander mit klarer Zuordnung.','A left preparation pane and a larger right live preview/result pane, connected by numbered labeled workflow steps in a slim header.'],
  ['structured-overview','Strukturierte Übersicht','Eine ruhige Übersicht zeigt die wichtigen Einstiegspunkte und Details der Auswahl.','An asymmetric but disciplined overview: one dominant section, two small useful context regions and a right detail column.'],
  ['memory-anchor','Kontextanker','Filter, letzte Auswahl und offene Aufgaben bleiben während der Arbeit sichtbar.','A persistent compact context anchor with current selection and draft state, main workspace, related evidence drawer with no floating clutter.'],
  ['compact-professional','Kompakter Arbeitsplatz','Präzise verdichtete Bereiche schaffen mehr Platz für Daten bei klarer Hierarchie.','A dense professional arrangement with legible 14px-equivalent data, compact non-overlapping toolbars, clear separators and enlarged main target controls.'],
  ['calm-workflow','Ruhiger Arbeitsfluss','Wenige klar gegliederte Bereiche führen vom Einstieg bis zum sichtbaren Ergebnis.','A calm linear task hierarchy inside the existing desktop shell: compact preparation area, dominant working stage, concise outcome and next action.'],
].map(([slug,name,idea,layout])=>({slug,name,idea,layout,level:'Corporate Design'}));

const views = [
  ['sql','SQL-Arbeitsplatz','A SQL editor with a credible 7-line SELECT joining public.users and orders, a results grid of 8 rows, query tabs, Ausführen, Explain, 248 Zeilen and 12 ms. Show active filters and selected-row details.',['cognitive-load','flow','doherty-threshold','working-memory']],
  ['table','Tabellen-Explorer','A wide public.users grid with 10 records, id, name, email, status, created_at; sort indicators, filter chips, selected cell, type-aware row detail and 2 pending edits with Prüfen.',['law-of-proximity','selective-attention','zeigarnik-effect','fittss-law']],
  ['schema','ER-Diagramm','An ER diagram containing 6 clean table cards for users, orders, order_items, products, payments and addresses, PK/FK badges, proper labeled relationship connectors, minimap, selected-table column inspector.',['law-of-uniform-connectedness','mental-model','law-of-common-region','working-memory']],
  ['builder','Query Builder','A visual SQL builder with selected users and orders, a real join condition, grouped fields and filters, readable generated SQL preview and a compact sample result grid. One Ausführen primary action.',['teslers-law','chunking','hicks-law','postels-law']],
  ['explain','Ausführungsplan','A real-looking execution plan: 84 ms total, plan tree with Hash Join and Index Scan nodes, honest percentage bars, selected-node evidence and source SQL, one Optimieren action with contextual help.',['cognitive-bias','law-of-uniform-connectedness','selective-attention','pareto-principle']],
  ['monitor','Live-Monitor','A live database monitor: sessions, throughput, CPU and locks; a large readable activity chart, an active query table and selected-session details. Show timestamps, running state and Stoppen, no fabricated improvement claims.',['doherty-threshold','selective-attention','cognitive-bias','law-of-proximity']],
  ['health','Datenbank-Health','A database health assessment with 4 grouped checks, factual statuses, one index warning with affected table and supporting evidence, a prioritized issue list, resolved-check summary.',['von-restorff-effect','pareto-principle','law-of-common-region','peak-end-rule']],
  ['dashboard','Datenbankübersicht','A database overview with size 122 MB, 6 tables, active connection and schema; restrained KPI blocks, useful size trend and the main object list with selection details and direct SQL action.',['mental-model','chunking','serial-position-effect','occams-razor']],
  ['history','Abfrageverlauf','Query history with grouped dates, a searchable list, SQL snippet, execution time, source connection, saved draft indicator and a large selected-query result preview. Clearly show Erneut ausführen.',['working-memory','zeigarnik-effect','law-of-similarity','flow']],
  ['automation','Automatisierung','A scheduled query workflow with labeled connected steps Abfrage, Export, Ziel; schedule and next run, factual recent-run log, execution status and primary Speichern. No invented urgent countdowns.',['law-of-uniform-connectedness','parkinsons-law','goal-gradient-effect','postels-law']],
  ['notebook','SQL-Notebook','A SQL notebook combining a short German analysis note, two numbered SQL cells, a useful result grid and a small sales chart. A clear outline, actual unfinished cell badge, run-cell controls and final outcome.',['flow','chunking','zeigarnik-effect','peak-end-rule']],
  ['ai','AI-Arbeitsbereich','A database AI workspace showing a German request Umsatz nach Monat, a readable proposed SQL query with named data sources, result preview and explicit Prüfen before execution. Clear read-only scope and grounded evidence, no opaque confidence score.',['cognitive-bias','teslers-law','mental-model','working-memory']],
  ['data-compare','Datenvergleich','Two synchronized result tables comparing staging and production with labeled source headers, aligned highlighted differences, totals of changed rows, selected-change detail and review before applying anything.',['law-of-similarity','working-memory','selective-attention','cognitive-bias']],
  ['schema-compare','Schema-Vergleich','Schema comparison staging vs production: a meaningful object diff tree, exact before and after column definitions, readable migration SQL preview, risk annotation with text and icon and primary Änderungen prüfen.',['law-of-similarity','law-of-common-region','teslers-law','von-restorff-effect']],
  ['transactions','Transaktionsprüfung','A transaction review showing 3 pending row edits, exact previous and proposed values, affected-row count and readable SQL, separate Verwerfen and primary Prüfen/Bestätigen controls with clear target connection.',['zeigarnik-effect','working-memory','fittss-law','peak-end-rule']],
  ['connections','Verbindungen','Connection manager with 6 named connections grouped development, staging, production; database family labels, a selected PostgreSQL connection form, masked password, URL import, Testen and specific validation feedback.',['choice-overload','postels-law','mental-model','paradox-of-the-active-user']],
  ['import','Datenimport','A CSV import workflow at step 2 of 3 with truthful mapping progress, source preview, target columns and types, 1 clearly described invalid date, a useful sample table and primary Vorschau prüfen.',['goal-gradient-effect','hicks-law','postels-law','teslers-law']],
  ['storage','Objektspeicher','An object-storage workspace with bucket outline, prefix breadcrumbs, file table showing CSV and Parquet names, size and last modified, selected object metadata and explicit upload progress with cancel.',['mental-model','doherty-threshold','law-of-proximity','working-memory']],
  ['settings','Einstellungen','Appearance and workflow settings with familiar vertical category navigation, labeled grouped setting rows, light/dark preview, density options, helpful descriptions, precise default/reset action and one Speichern action.',['jakobs-law','choice-overload','law-of-common-region','law-of-similarity']],
  ['mcp','MCP und Zugriff','An MCP access workspace with server state, named tools and permissions, connection scope, a factual request log, selected-tool details, masked credential and a clear Verbindung testen action.',['mental-model','cognitive-bias','chunking','selective-attention']],
].map(([slug,name,brief,lawIds])=>({slug,name,brief,lawIds}));

const brand = 'Use the supplied real current l8db screenshot strictly as CORPORATE DESIGN reference, not as a layout to copy. Preserve the small plain l8db wordmark, IBM Plex Sans-style sans serif UI text, monospace SQL/data, thin Lucide-style outline icons, cool neutral surfaces, very low-chroma muted slate/steel-blue accents, fine gray borders, small softly rounded rectangular controls, about 12px panel radii, restrained shadows and professional readable dense grids. Retain the recognizable compact 46px app header, centered Suchen command pill, 56px left feature rail and contextual object navigation. No new logo, neon, gradient decoration, glass, 3D, serif display font, whimsical furniture or arbitrary colorful brand palette. Semantic green/amber/red only in small labeled status/error areas. Make a fresh polished innovative but plausible l8db DESKTOP UI screen, direct flat screenshot filling the image, landscape 1600x1000 composition, no device frame, poster title, collage or explanatory annotations outside the app. Prefer clear German UI labels and realistic restrained technical content.';
const ux = 'Laws of UX design requirements, adapted to the actual screen: '+laws.map(l=>l.prompt).join(' ')+' Separate primary, secondary and destructive actions. Pair status colors with words/icons. Preserve comfortable text contrast, clear focus styling and space around click targets; do not cram controls to match the reference density. Show only states relevant to this view. This is a static design proposal; do not claim measured latency, keyboard operation or accessibility compliance.';
const images=[];
for(let i=0;i<layouts.length;i++){
  for(let j=0;j<5;j++){
    const view=views[(i*5+j)%views.length];
    const style=layouts[i];
    const id=String(101+i*5+j);
    const tone=(Math.floor(i/4)+j)%2===0?'Hell':'Dunkel';
    const theme=tone==='Hell'?'LIGHT theme: pale cool off-white/silver background and white inset surfaces, dark ink type, muted steel-blue selection and primary controls.':'DARK theme: near-black cool blue-charcoal background, subtly lighter slate inset panels, off-white type and desaturated pale steel-blue accents. Avoid crushed black content or glowing borders.';
    const prompt=[brand,theme,'Distinct layout concept '+style.name+': '+style.layout,'Required view '+view.name+': '+view.brief,ux,'Give the actual primary working content at least half of the screenshot; use only useful context panes. Crisp readable professional product mockup, coherent component system.'].join('\n\n');
    images.push({id,style:style.name,styleSlug:style.slug,tone,level:style.level,idea:style.idea,view:view.name,viewSlug:view.slug,file:'images/'+id+'-'+style.slug+'-'+view.slug+'.png',reference:'references/l8db-current-'+(tone==='Hell'?'light':'dark')+'.png',lawIds:view.lawIds,prompt,status:'pending'});
  }
}
mkdirSync(join(root,'images'),{recursive:true});
mkdirSync(join(root,'thumbnails'),{recursive:true});
writeFileSync(join(root,'manifest.json'),JSON.stringify({project:'l8db',count:100,collection:'Corporate Design · Entwürfe 101–200',method:'built-in image_gen',source:'https://lawsofux.com/',styles:layouts,views,images},null,2)+'\n');
writeFileSync(join(root,'ux-principles.json'),JSON.stringify({source:'https://lawsofux.com/',reviewed:'2026-10-08',principleCount:laws.length,scope:'Designkriterien für statische Entwürfe; Interaktion und empirische Effekte sind nicht durch Bilder nachgewiesen.',principles:laws},null,2)+'\n');
writeFileSync(join(root,'.gitignore'),'batch-*.json\nl8db-corporate-100-designs.zip\n*.local\n');
console.log(JSON.stringify({images:images.length,layouts:layouts.length,views:views.length,principles:laws.length}));
