pub const FIRST_DE: &[&str] = &[
    "Anna",
    "Ben",
    "Clara",
    "David",
    "Emma",
    "Felix",
    "Greta",
    "Hannah",
    "Jonas",
    "Julia",
    "Karl",
    "Laura",
    "Leon",
    "Lina",
    "Lukas",
    "Marie",
    "Max",
    "Mia",
    "Noah",
    "Paul",
    "Sophie",
    "Tim",
    "Lea",
    "Jan",
    "Katharina",
    "Moritz",
    "Sabine",
    "Stefan",
    "Ursula",
    "Wolfgang",
];

pub const LAST_DE: &[&str] = &[
    "Müller",
    "Schmidt",
    "Schneider",
    "Fischer",
    "Weber",
    "Meyer",
    "Wagner",
    "Becker",
    "Schulz",
    "Hoffmann",
    "Schäfer",
    "Koch",
    "Bauer",
    "Richter",
    "Klein",
    "Wolf",
    "Schröder",
    "Neumann",
    "Schwarz",
    "Zimmermann",
    "Braun",
    "Krüger",
    "Hofmann",
    "Hartmann",
    "Lange",
    "Werner",
    "Krause",
    "Lehmann",
    "Köhler",
    "Maier",
];

pub const CITY_DE: &[&str] = &[
    "Berlin",
    "Hamburg",
    "München",
    "Köln",
    "Frankfurt am Main",
    "Stuttgart",
    "Düsseldorf",
    "Leipzig",
    "Dortmund",
    "Essen",
    "Bremen",
    "Dresden",
    "Hannover",
    "Nürnberg",
    "Duisburg",
    "Bochum",
    "Wuppertal",
    "Bielefeld",
    "Bonn",
    "Münster",
    "Mannheim",
    "Karlsruhe",
    "Augsburg",
    "Freiburg",
    "Kiel",
];

pub const STREET_DE: &[&str] = &[
    "Hauptstraße",
    "Schulstraße",
    "Gartenstraße",
    "Bahnhofstraße",
    "Dorfstraße",
    "Bergstraße",
    "Lindenstraße",
    "Kirchstraße",
    "Waldstraße",
    "Ringstraße",
    "Rosenweg",
    "Birkenweg",
    "Am Markt",
    "Mühlenweg",
    "Friedhofstraße",
    "Goethestraße",
    "Schillerstraße",
    "Parkstraße",
];

pub const FIRST_EN: &[&str] = &[
    "James",
    "Mary",
    "John",
    "Patricia",
    "Robert",
    "Jennifer",
    "Michael",
    "Linda",
    "William",
    "Elizabeth",
    "David",
    "Barbara",
    "Richard",
    "Susan",
    "Joseph",
    "Jessica",
    "Thomas",
    "Sarah",
    "Charles",
    "Karen",
    "Daniel",
    "Nancy",
    "Matthew",
    "Lisa",
    "Emily",
    "Oliver",
    "Grace",
    "Henry",
    "Olivia",
    "Jack",
];

pub const LAST_EN: &[&str] = &[
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Garcia",
    "Miller",
    "Davis",
    "Rodriguez",
    "Martinez",
    "Wilson",
    "Anderson",
    "Taylor",
    "Thomas",
    "Moore",
    "Jackson",
    "Martin",
    "Lee",
    "Thompson",
    "White",
    "Harris",
    "Clark",
    "Lewis",
    "Robinson",
    "Walker",
    "Young",
    "Allen",
    "King",
    "Wright",
    "Scott",
];

pub const CITY_EN: &[&str] = &[
    "New York",
    "London",
    "Chicago",
    "Houston",
    "Phoenix",
    "Manchester",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "Birmingham",
    "Austin",
    "Seattle",
    "Denver",
    "Boston",
    "Leeds",
    "Glasgow",
    "Portland",
    "Atlanta",
    "Miami",
    "Liverpool",
    "Bristol",
    "Detroit",
    "Toronto",
    "Dublin",
];

pub const STREET_EN: &[&str] = &[
    "Main Street",
    "High Street",
    "Oak Avenue",
    "Maple Drive",
    "Park Road",
    "Church Lane",
    "Elm Street",
    "Station Road",
    "Victoria Road",
    "Mill Lane",
    "Cedar Court",
    "Pine Street",
    "Washington Avenue",
    "Lake View",
    "Sunset Boulevard",
    "King Street",
    "Queen Street",
    "Bridge Road",
];

pub const COUNTRY_DE: &[&str] = &[
    "Deutschland",
    "Österreich",
    "Schweiz",
    "Frankreich",
    "Italien",
    "Spanien",
    "Niederlande",
    "Belgien",
    "Polen",
    "Dänemark",
    "Schweden",
    "Norwegen",
];

pub const COUNTRY_EN: &[&str] = &[
    "United States",
    "United Kingdom",
    "Canada",
    "Australia",
    "Ireland",
    "Germany",
    "France",
    "Spain",
    "Italy",
    "Netherlands",
    "Sweden",
    "Norway",
];

pub const COMPANY_DE: &[&str] = &["GmbH", "AG", "KG", "GmbH & Co. KG", "e.K.", "UG"];

pub const COMPANY_EN: &[&str] = &["Inc.", "LLC", "Ltd.", "Corp.", "Group", "Partners"];

pub const DOMAIN_DE: &[&str] = &["example.de", "beispiel.de", "test.de", "mail.example.org"];

pub const DOMAIN_EN: &[&str] = &["example.com", "example.org", "test.com", "mail.example.net"];

pub const WORDS: &[&str] = &[
    "lorem",
    "ipsum",
    "dolor",
    "sit",
    "amet",
    "consectetur",
    "adipiscing",
    "elit",
    "sed",
    "do",
    "eiusmod",
    "tempor",
    "incididunt",
    "ut",
    "labore",
    "et",
    "dolore",
    "magna",
    "aliqua",
    "enim",
    "ad",
    "minim",
    "veniam",
    "quis",
    "nostrud",
    "exercitation",
    "ullamco",
    "laboris",
    "nisi",
    "aliquip",
    "commodo",
    "consequat",
];
