#!/usr/bin/env bash
set -euo pipefail
prefix="${L8DB_VERSIONING_LAB_PREFIX:-l8db-versioning-lab}"
dir="${L8DB_VERSIONING_LAB_DIR:-${TMPDIR:-/tmp}/l8db-versioning-lab}"
dir="${dir%/}"
pg="$prefix-pg"
oracle="$prefix-oracle"
password=l8dbtest
if [ "${1:-up}" = down ]; then
  docker rm -f -v "$pg" "$oracle" >/dev/null 2>&1 || true
  rm -rf "$dir"
  exit 0
fi
docker run -d --name "$pg" -p 127.0.0.1:55440:5432 -e POSTGRES_PASSWORD="$password" postgres:18 >/dev/null
docker run -d --name "$oracle" -p 127.0.0.1:55441:1521 -e ORACLE_PASSWORD="$password" \
  gvenzl/oracle-free:23-slim >/dev/null
for _ in $(seq 1 120); do
  docker exec "$pg" pg_isready -U postgres >/dev/null 2>&1 && break
  sleep 1
done
for _ in $(seq 1 180); do
  docker logs "$oracle" 2>&1 | grep -q "DATABASE IS READY TO USE" && break
  sleep 2
done
docker logs "$oracle" 2>&1 | grep -q "DATABASE IS READY TO USE"
{
  echo "WHENEVER SQLERROR EXIT FAILURE ROLLBACK"
  echo "ALTER SESSION SET CONTAINER=FREEPDB1;"
  echo "GRANT EXECUTE ON SYS.DBMS_LOCK TO SYSTEM;"
  for schema in L8DB_DEV L8DB_CUSTOMER_A L8DB_CUSTOMER_B; do
    cat <<SQL
CREATE USER $schema IDENTIFIED BY $password;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER TO $schema;
ALTER USER $schema QUOTA 100M ON USERS;
GRANT EXECUTE ON SYS.DBMS_LOCK TO $schema;
CREATE TABLE $schema.CUSTOMERS (ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, NAME VARCHAR2(200) NOT NULL, EMAIL VARCHAR2(200) NOT NULL UNIQUE);
CREATE TABLE $schema.ORDERS (ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, CUSTOMER_ID NUMBER NOT NULL REFERENCES $schema.CUSTOMERS(ID), TOTAL NUMBER(12,2) NOT NULL CHECK (TOTAL >= 0));
SQL
  done
  echo "EXIT;"
} | docker exec -i "$oracle" sqlplus -s "/ as sysdba" >/dev/null
mkdir -p "$dir/repos"
umask 077
cat >"$dir/lab.json" <<JSON
{
  "root": "$dir/repos",
  "repo": "$dir/repos",
  "postgresUrl": "postgresql://postgres:$password@127.0.0.1:55440/postgres?sslmode=disable",
  "oracleUrl": "oracle://system:$password@127.0.0.1:55441/FREEPDB1"
}
JSON
chmod 600 "$dir/lab.json"
cat <<INFO
Versioning lab ready
  export L8DB_VERSIONING_LAB=$dir/lab.json
  export L8DB_VERSIONING_ORACLE_TEST_URL_DEV=oracle://L8DB_DEV:$password@127.0.0.1:55441/FREEPDB1
  export L8DB_VERSIONING_ORACLE_TEST_URL_A=oracle://L8DB_CUSTOMER_A:$password@127.0.0.1:55441/FREEPDB1
  export L8DB_VERSIONING_ORACLE_TEST_URL_B=oracle://L8DB_CUSTOMER_B:$password@127.0.0.1:55441/FREEPDB1
  Stop: scripts/versioning-lab.sh down
INFO
