import type { TourChapter } from "@/lib/tour/types";

export const TOUR_CHAPTERS: TourChapter[] = [
  {
    id: "welcome",
    title: "Willkommen",
    summary: "Was l8db ist und wie die Tour funktioniert.",
    steps: [
      {
        id: "hello",
        title: "Willkommen bei l8db",
        body: "Mit l8db schaust du in Datenbanken hinein: Du siehst Tabellen wie in einer Excel-Liste, kannst Werte ändern und Fragen an die Datenbank stellen. Du brauchst kein Vorwissen. So geht die Tour: Ein Bereich wird hell hervorgehoben, der Kasten mit 👉 sagt dir genau, was du tun sollst. „Zurück“ geht einen Schritt zurück, „−“ versteckt die Tour kurz, „×“ beendet sie. Du kannst nichts kaputt machen.",
        action: "Klicke unten rechts auf „Weiter“ (oder drücke die Pfeiltaste →).",
        route: "/",
        side: "over",
      },
      {
        id: "header-nav",
        title: "Die Knöpfe oben links",
        body: "Das Logo bringt dich immer zurück zur Startseite. Daneben: SQL-Editor (Fragen an die Datenbank schreiben), ER-Diagramm (Bild, wie Tabellen zusammenhängen), Über l8db und Neuigkeiten.",
        action: "Schau dir die hervorgehobenen Knöpfe an und klicke dann auf „Weiter“.",
        target: "[data-tour='header-nav']",
        side: "bottom",
      },
      {
        id: "header-search",
        title: "Die Suche findet alles",
        body: "Wenn du etwas nicht findest: Klicke hier oder drücke ⌘K (Mac) bzw. Strg+K (Windows/Linux). Dann tippst du einfach, was du suchst — zum Beispiel einen Tabellennamen — und drückst Enter.",
        action: "Merke dir: ⌘K / Strg+K = Suche. Klicke auf „Weiter“.",
        target: "[data-tour='header-search']",
        side: "bottom",
      },
      {
        id: "header-actions",
        title: "Die Knöpfe oben rechts",
        body: "Der Pfeil-Kreis lädt alles neu, falls etwas veraltet aussieht. Daneben: Änderungsprotokoll, Hell/Dunkel-Modus, Treiber und das Zahnrad für die Einstellungen. In den Einstellungen kannst du diese Tour jederzeit neu starten.",
        action: "Klicke auf „Weiter“.",
        target: "[data-tour='header-actions']",
        side: "bottom",
      },
    ],
  },
  {
    id: "connections",
    title: "Verbindung anlegen",
    summary: "l8db sagen, welche Datenbank du öffnen willst.",
    steps: [
      {
        id: "connections-page",
        title: "Was ist eine Verbindung?",
        body: "Eine Verbindung ist wie ein Lesezeichen: Sie merkt sich, wo deine Datenbank liegt und wie du dich anmeldest. Hier siehst du alle gespeicherten Verbindungen. Passwörter werden sicher im Schlüsselbund deines Computers gespeichert.",
        action: "Klicke auf „Weiter“ — gleich legen wir zusammen eine Verbindung an.",
        route: "/connections",
        target: "[data-tour='connections-page']",
        side: "bottom",
      },
      {
        id: "add-connection",
        title: "Neue Verbindung starten",
        body: "Über „Neu“ öffnet sich ein Formular für eine neue Verbindung. Die Tour geht automatisch weiter, sobald das Formular offen ist.",
        action: "Klicke auf den hervorgehobenen Knopf „Neu“.",
        target: "[data-tour='connection-add']",
        autoClick: "[data-tour='connection-add']",
        wait: { type: "element", selector: "[data-tour='connection-editor']" },
        waitHint: "Die Tour wartet, bis du auf „Neu“ geklickt hast…",
        skipIf: "editor-open",
        side: "left",
      },
      {
        id: "connection-editor",
        title: "Das Formular ausfüllen",
        body: "1. Wähle oben die Art der Datenbank (zum Beispiel PostgreSQL oder MySQL). 2. Gib der Verbindung einen Namen, den du wiedererkennst. 3. Trage Adresse (Host), Benutzer und Passwort ein — die bekommst du von der Person, die die Datenbank betreut. Hast du eine Datei (SQLite/DuckDB), wählst du einfach die Datei aus.",
        action: "Fülle die Felder aus. Wenn du fertig bist, klicke auf „Weiter“.",
        target: "[data-tour='connection-editor']",
        side: "right",
      },
      {
        id: "save-connection",
        title: "Testen und speichern",
        body: "Mit „Testen“ prüfst du, ob die Daten stimmen. Wenn alles grün ist, speicherst du die Verbindung. Du hast noch keine Zugangsdaten? Kein Problem: Klicke auf „Überspringen“ und mach die Tour trotzdem weiter.",
        action: "Speichere die Verbindung — oder klicke auf „Überspringen“.",
        target: "[data-tour='connection-editor']",
        wait: { type: "connection-added" },
        waitHint: "Die Tour wartet, bis die Verbindung gespeichert ist…",
        side: "top",
      },
    ],
  },
  {
    id: "workspace",
    title: "Verbinden",
    summary: "Eine Datenbank öffnen und die Startseite verstehen.",
    steps: [
      {
        id: "connect-now",
        title: "Datenbank öffnen",
        body: "Eine gespeicherte Verbindung musst du noch öffnen, erst dann siehst du Daten. Das ist wie ein Doppelklick auf einen Ordner. Ohne Verbindung überspringt die Tour die Schritte, die eine offene Datenbank brauchen.",
        action:
          "Klicke auf eine gespeicherte Verbindung, um sie zu öffnen — oder auf „Überspringen“.",
        route: "/",
        wait: { type: "active-connection" },
        waitHint: "Die Tour wartet, bis eine Datenbank geöffnet ist…",
        skipIf: "has-active",
        side: "over",
      },
      {
        id: "dashboard",
        title: "Deine Startseite",
        body: "Hier siehst du, mit welcher Datenbank du gerade verbunden bist, und wie viele Tabellen, Ansichten und andere Dinge darin stecken.",
        action: "Schau dir die Zahlen an und klicke auf „Weiter“.",
        route: "/",
        target: "[data-tour='dashboard']",
        skipIf: "no-connection",
        side: "bottom",
      },
      {
        id: "dashboard-actions",
        title: "Schnell loslegen",
        body: "„SQL-Abfrage“ öffnet einen leeren Editor, in dem du Fragen an die Datenbank schreibst. „Aktualisieren“ lädt die Liste neu, wenn jemand anderes etwas geändert hat.",
        action: "Klicke auf „Weiter“.",
        target: "[data-tour='dashboard-actions']",
        skipIf: "no-connection",
        side: "left",
      },
    ],
  },
  {
    id: "explorer",
    title: "Die Seitenleiste",
    summary: "Links findest du alle Tabellen.",
    steps: [
      {
        id: "sidebar-connection",
        title: "Welche Datenbank ist offen?",
        body: "Hier oben links steht immer, welche Verbindung gerade offen ist. Klickst du darauf, kannst du zu einer anderen Datenbank wechseln.",
        action: "Klicke auf „Weiter“.",
        route: "/",
        target: "[data-tour='sidebar-connection']",
        skipIf: "no-connection",
        side: "right",
      },
      {
        id: "sidebar-scope",
        title: "Datenbank und Schema",
        body: "Eine Datenbank ist wie ein Schrank, ein Schema wie eine Schublade darin. Hier wählst du, welche Schublade du gerade anschaust. Meistens passt die Voreinstellung schon.",
        action: "Lass alles, wie es ist, und klicke auf „Weiter“.",
        target: "[data-tour='sidebar-scope']",
        skipIf: "no-connection",
        side: "right",
      },
      {
        id: "sidebar-tabs",
        title: "Was liegt in der Schublade?",
        body: "Die Reiter sortieren den Inhalt: „Tabellen“ enthalten die eigentlichen Daten. Die anderen Reiter (Views, Funktionen …) brauchst du am Anfang nicht.",
        action: "Bleib beim Reiter „Tabellen“ und klicke auf „Weiter“.",
        target: "[data-tour='sidebar-tabs']",
        skipIf: "no-connection",
        side: "right",
      },
      {
        id: "sidebar-search",
        title: "Tabelle suchen",
        body: "Bei vielen Tabellen tippst du hier einfach einen Teil des Namens ein — die Liste zeigt dann nur noch passende Tabellen.",
        action: "Klicke auf „Weiter“. Gleich öffnest du eine Tabelle.",
        target: "[data-tour='sidebar-search']",
        skipIf: "no-connection",
        side: "right",
      },
      {
        id: "open-table",
        title: "Eine Tabelle öffnen",
        body: "Ein Klick auf einen Tabellennamen zeigt dir ihre Daten. Die Tour geht automatisch weiter, sobald die Tabelle offen ist.",
        action: "Klicke auf die hervorgehobene Tabelle.",
        target: "[data-tour='sidebar-table']",
        autoClick: "[data-tour='sidebar-table']",
        tableRoute: true,
        wait: { type: "route", includes: "/tables/" },
        waitHint: "Die Tour wartet, bis du eine Tabelle geöffnet hast…",
        skipIf: "no-tables",
        side: "right",
      },
    ],
  },
  {
    id: "tables",
    title: "Daten ansehen und ändern",
    summary: "Zeilen lesen, filtern, bearbeiten, exportieren.",
    steps: [
      {
        id: "table-grid",
        title: "Deine Daten",
        body: "So sieht eine Tabelle aus: Jede Zeile ist ein Eintrag, jede Spalte eine Eigenschaft. Klick auf eine Spaltenüberschrift sortiert. Unten blätterst du zur nächsten Seite.",
        action: "Scrolle ruhig ein bisschen durch die Daten und klicke dann auf „Weiter“.",
        tableRoute: true,
        target: "[data-tour='data-grid']",
        skipIf: "no-tables",
        side: "top",
      },
      {
        id: "table-edit",
        title: "Einen Wert ändern",
        body: "Doppelklicke auf eine Zelle, um ihren Wert zu ändern. Enter speichert, Esc bricht ab. Mit einem Rechtsklick auf eine Zeile kannst du sie kopieren oder löschen. Tipp: Probiere das erst in einer Test-Datenbank aus.",
        action:
          "Merke dir: Doppelklick = bearbeiten, Enter = speichern, Esc = abbrechen. Klicke auf „Weiter“.",
        tableRoute: true,
        target: "[data-tour='data-grid']",
        skipIf: "no-tables",
        side: "top",
      },
      {
        id: "table-filter",
        title: "Nur bestimmte Zeilen zeigen",
        body: "Mit dem Filter zeigst du nur Zeilen, die dich interessieren — zum Beispiel alle Kunden aus Berlin. Wähle eine Spalte, eine Bedingung und einen Wert. Häufige Filter kannst du speichern.",
        action: "Klicke auf „Weiter“.",
        tableRoute: true,
        target: "[data-tour='table-filter']",
        skipIf: "no-tables",
        side: "bottom",
      },
      {
        id: "table-toolbar",
        title: "Spalten, Export und mehr",
        body: "Hier oben wechselst du zwischen den Daten und dem Aufbau der Tabelle („Spalten“). Über „Export“ speicherst du die Daten als Datei (CSV für Excel oder JSON).",
        action: "Klicke auf „Weiter“.",
        tableRoute: true,
        target: "[data-tour='table-toolbar']",
        skipIf: "no-tables",
        side: "bottom",
      },
      {
        id: "table-add",
        title: "Neue Zeile hinzufügen",
        body: "„Neue Zeile“ öffnet ein Formular. Fülle die Felder aus und speichere — schon ist der Eintrag in der Datenbank.",
        action: "Klicke auf „Weiter“.",
        tableRoute: true,
        target: "[data-tour='table-add']",
        skipIf: "no-tables",
        side: "left",
      },
    ],
  },
  {
    id: "sql",
    title: "Fragen stellen (SQL)",
    summary: "Mit SQL genau die Daten holen, die du brauchst.",
    steps: [
      {
        id: "query-page",
        title: "Der SQL-Editor",
        body: "SQL ist die Sprache, mit der du der Datenbank Fragen stellst. Beispiel: SELECT * FROM kunden; heißt „Zeig mir alle Kunden“. Jeder Editor ist ein eigener Reiter, wie im Browser.",
        action: "Klicke auf „Weiter“.",
        route: "/query",
        target: "[data-tour='query-toolbar']",
        side: "bottom",
      },
      {
        id: "query-run",
        title: "Frage abschicken",
        body: "Schreibe deine Frage in das große Textfeld und klicke auf „Ausführen“ (oder ⌘/Strg+Enter). Das Ergebnis erscheint darunter als Tabelle. Hast du Text markiert, läuft nur die Markierung.",
        action: "Probiere es aus: Tippe SELECT 1; und klicke auf „Ausführen“. Dann „Weiter“.",
        target: "[data-tour='query-run']",
        side: "bottom",
      },
      {
        id: "query-history",
        title: "Speichern und Verlauf",
        body: "Gute Abfragen kannst du speichern, damit du sie später wieder findest. Der Verlauf merkt sich automatisch alles, was du ausgeführt hast.",
        action: "Klicke auf „Weiter“.",
        target: "[data-tour='query-history']",
        side: "bottom",
      },
      {
        id: "query-builder",
        title: "Ohne SQL: der Abfrage-Baukasten",
        body: "Du willst kein SQL tippen? Im Abfrage-Baukasten klickst du Tabellen und Spalten einfach zusammen, l8db schreibt das SQL für dich.",
        action: "Schau dich kurz um und klicke dann auf „Weiter“.",
        route: "/query-builder",
        skipIf: "no-connection",
        side: "over",
      },
    ],
  },
  {
    id: "diagram",
    title: "ER-Diagramm",
    summary: "Sehen, wie Tabellen zusammenhängen.",
    steps: [
      {
        id: "er",
        title: "Tabellen als Bild",
        body: "Jeder Kasten ist eine Tabelle, jede Linie eine Verbindung zwischen zwei Tabellen (zum Beispiel: eine Bestellung gehört zu einem Kunden). Mit dem Mausrad zoomst du, mit gedrückter Maustaste verschiebst du das Bild.",
        action: "Zoome und verschiebe ein wenig, dann klicke auf „Weiter“.",
        route: "/er-diagram",
        target: "[data-tour='er-page']",
        side: "left",
      },
    ],
  },
  {
    id: "transactions",
    title: "Sicher ändern",
    summary: "Änderungen erst sammeln, dann bestätigen.",
    steps: [
      {
        id: "tx-toggle",
        title: "Das Änderungsprotokoll",
        body: "Wenn du vorsichtig sein willst, sammelt l8db deine Änderungen erst, statt sie sofort zu speichern. Dieser Knopf öffnet die Liste der gesammelten Änderungen. Die Tour öffnet sie jetzt für dich.",
        action: "Klicke auf „Weiter“.",
        route: "/",
        target: "[data-tour='header-tx']",
        openTx: true,
        side: "bottom",
      },
      {
        id: "tx-panel",
        title: "Bestätigen oder verwerfen",
        body: "„Commit“ heißt: Ja, speichere alles wirklich. „Rollback“ heißt: Vergiss alles, nichts wird gespeichert. Ob Änderungen gesammelt oder sofort gespeichert werden, stellst du in den Einstellungen ein.",
        action: "Merke dir: Commit = speichern, Rollback = verwerfen. Klicke auf „Weiter“.",
        target: "[data-tour='tx-panel']",
        side: "left",
      },
    ],
  },
  {
    id: "tools",
    title: "Weitere Werkzeuge",
    summary: "Notizbuch, Import, Backup, Monitor.",
    steps: [
      {
        id: "notebook",
        title: "Notizbuch",
        body: "Im Notizbuch mischst du Text und SQL-Abfragen auf einer Seite — praktisch, um eine Auswertung Schritt für Schritt aufzuschreiben und später erneut auszuführen.",
        action: "Klicke auf „Weiter“.",
        route: "/notebook",
        skipIf: "no-connection",
        side: "over",
      },
      {
        id: "import",
        title: "Daten importieren",
        body: "Du hast eine CSV- oder Excel-ähnliche Datei? Hier lädst du sie in eine Tabelle. l8db zeigt dir vorher eine Vorschau, damit nichts schiefgeht.",
        action: "Klicke auf „Weiter“.",
        route: "/import",
        skipIf: "no-connection",
        side: "over",
      },
      {
        id: "backup",
        title: "Sicherung (Backup)",
        body: "Bevor du größere Änderungen machst: Erstelle hier eine Sicherung. Damit kannst du den alten Stand jederzeit wiederherstellen.",
        action: "Klicke auf „Weiter“.",
        route: "/backup",
        skipIf: "no-connection",
        side: "over",
      },
      {
        id: "monitor",
        title: "Monitor",
        body: "Der Monitor zeigt live, wie beschäftigt die Datenbank gerade ist und welche Abfragen laufen. Wird etwas langsam, schaust du hier zuerst nach.",
        action: "Klicke auf „Weiter“.",
        route: "/monitor",
        target: "[data-tour='monitor']",
        skipIf: "no-connection",
        side: "top",
      },
    ],
  },
  {
    id: "system",
    title: "Einstellungen und Hilfe",
    summary: "l8db anpassen und Hilfe finden.",
    steps: [
      {
        id: "drivers",
        title: "Treiber",
        body: "Für jede Datenbank-Art braucht l8db einen passenden Treiber. Hier siehst du, welche bereit sind. Fehlt einer, kannst du ihn hier installieren.",
        action: "Klicke auf „Weiter“.",
        route: "/drivers",
        target: "[data-tour='drivers-page']",
        side: "bottom",
      },
      {
        id: "settings",
        title: "Einstellungen",
        body: "Hier stellst du alles nach deinem Geschmack ein: Hell/Dunkel, Schriftgröße, wie viele Zeilen angezeigt werden und ob Änderungen erst gesammelt werden sollen.",
        action: "Klicke auf „Weiter“.",
        route: "/settings",
        target: "[data-tour='settings-page']",
        side: "bottom",
      },
      {
        id: "docs",
        title: "Hilfe und Anleitungen",
        body: "Wenn du nicht weiterweißt, findest du hier ausführliche Anleitungen zu allen Funktionen — auch zu Profi-Werkzeugen wie dem Vergleich zweier Datenbanken.",
        action: "Klicke auf „Weiter“.",
        route: "/docs",
        side: "over",
      },
      {
        id: "finish",
        title: "Geschafft! 🎉",
        body: "Du kennst jetzt alles Wichtige: Verbindung anlegen, Tabelle öffnen, Werte ändern, SQL ausführen und Hilfe finden. Du willst etwas nochmal sehen? Starte die Tour jederzeit unter Einstellungen → Produkttour neu, oder springe über „alle Kapitel“ direkt zu einem Thema.",
        action: "Klicke auf „Weiter“, um die Tour zu beenden.",
        route: "/",
        side: "over",
      },
    ],
  },
];
