/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReleaseNotesRouteImport } from './routes/release-notes'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppWorkspaceRouteImport } from './routes/_app._workspace'
import { Route as AppPlainRouteImport } from './routes/_app._plain'
import { Route as AppWorkspaceIndexRouteImport } from './routes/_app._workspace.index'
import { Route as AppWorkspaceSessionsRouteImport } from './routes/_app._workspace.sessions'
import { Route as AppWorkspaceSequencesRouteImport } from './routes/_app._workspace.sequences'
import { Route as AppWorkspaceReplicationRouteImport } from './routes/_app._workspace.replication'
import { Route as AppWorkspaceQueryBuilderRouteImport } from './routes/_app._workspace.query-builder'
import { Route as AppWorkspaceQueryRouteImport } from './routes/_app._workspace.query'
import { Route as AppWorkspaceImportRouteImport } from './routes/_app._workspace.import'
import { Route as AppWorkspaceErDiagramRouteImport } from './routes/_app._workspace.er-diagram'
import { Route as AppWorkspaceEnumsRouteImport } from './routes/_app._workspace.enums'
import { Route as AppWorkspaceCreateTableRouteImport } from './routes/_app._workspace.create-table'
import { Route as AppWorkspaceCompareRouteImport } from './routes/_app._workspace.compare'
import { Route as AppPlainAvailableExtensionsRouteImport } from './routes/_app._plain.available-extensions'
import { Route as AppWorkspaceQueryIndexRouteImport } from './routes/_app._workspace.query.index'
import { Route as AppWorkspaceUsersNameRouteImport } from './routes/_app._workspace.users.$name'
import { Route as AppWorkspaceQueryIdRouteImport } from './routes/_app._workspace.query.$id'
import { Route as AppWorkspaceExtensionsNameRouteImport } from './routes/_app._workspace.extensions.$name'
import { Route as AppWorkspaceViewEditorSchemaViewRouteImport } from './routes/_app._workspace.view-editor.$schema.$view'
import { Route as AppWorkspaceTablesSchemaTableRouteImport } from './routes/_app._workspace.tables.$schema.$table'
import { Route as AppWorkspacePackagesSchemaNameRouteImport } from './routes/_app._workspace.packages.$schema.$name'
import { Route as AppWorkspaceMatviewsSchemaNameRouteImport } from './routes/_app._workspace.matviews.$schema.$name'
import { Route as AppWorkspaceFunctionsSchemaNameRouteImport } from './routes/_app._workspace.functions.$schema.$name'
import { Route as AppWorkspaceAlterTableSchemaTableRouteImport } from './routes/_app._workspace.alter-table.$schema.$table'
import { Route as AppWorkspaceTriggersSchemaTableTriggerRouteImport } from './routes/_app._workspace.triggers.$schema.$table.$trigger'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleaseNotesRoute = ReleaseNotesRouteImport.update({
  id: '/release-notes',
  path: '/release-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppPlainRoute = AppPlainRouteImport.update({
  id: '/_plain',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceIndexRoute = AppWorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceSessionsRoute = AppWorkspaceSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceSequencesRoute = AppWorkspaceSequencesRouteImport.update({
  id: '/sequences',
  path: '/sequences',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceReplicationRoute = AppWorkspaceReplicationRouteImport.update({
  id: '/replication',
  path: '/replication',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceQueryBuilderRoute =
  AppWorkspaceQueryBuilderRouteImport.update({
    id: '/query-builder',
    path: '/query-builder',
    getParentRoute: () => AppWorkspaceRoute,
  } as any)
const AppWorkspaceQueryRoute = AppWorkspaceQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceImportRoute = AppWorkspaceImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceErDiagramRoute = AppWorkspaceErDiagramRouteImport.update({
  id: '/er-diagram',
  path: '/er-diagram',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceEnumsRoute = AppWorkspaceEnumsRouteImport.update({
  id: '/enums',
  path: '/enums',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceCreateTableRoute = AppWorkspaceCreateTableRouteImport.update({
  id: '/create-table',
  path: '/create-table',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceCompareRoute = AppWorkspaceCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppPlainAvailableExtensionsRoute =
  AppPlainAvailableExtensionsRouteImport.update({
    id: '/available-extensions',
    path: '/available-extensions',
    getParentRoute: () => AppPlainRoute,
  } as any)
const AppWorkspaceQueryIndexRoute = AppWorkspaceQueryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkspaceQueryRoute,
} as any)
const AppWorkspaceUsersNameRoute = AppWorkspaceUsersNameRouteImport.update({
  id: '/users/$name',
  path: '/users/$name',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceQueryIdRoute = AppWorkspaceQueryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppWorkspaceQueryRoute,
} as any)
const AppWorkspaceExtensionsNameRoute =
  AppWorkspaceExtensionsNameRouteImport.update({
    id: '/extensions/$name',
    path: '/extensions/$name',
    getParentRoute: () => AppWorkspaceRoute,
  } as any)
const AppWorkspaceViewEditorSchemaViewRoute =
  AppWorkspaceViewEditorSchemaViewRouteImport.update({
    id: '/view-editor/$schema/$view',
    path: '/view-editor/$schema/$view',
    getParentRoute: () => AppWorkspaceRoute,
  } as any)
const AppWorkspaceTablesSchemaTableRoute =
  AppWorkspaceTablesSchemaTableRouteImport.update({
    id: '/tables/$schema/$table',
    path: '/tables/$schema/$table',
    getParentRoute: () => AppWorkspaceRoute,
  } as any)
const AppWorkspacePackagesSchemaNameRoute =
  AppWorkspacePackagesSchemaNameRouteImport.update({
    id: '/packages/$schema/$name',
    path: '/packages/$schema/$name',
    getParentRoute: () => AppWorkspaceRoute,
  } as any)
const AppWorkspaceMatviewsSchemaNameRoute =
  AppWorkspaceMatviewsSchemaNameRouteImport.update({
    id: '/matviews/$schema/$name',
    path: '/matviews/$schema/$name',
    getParentRoute: () => AppWorkspaceRoute,
  } as any)
const AppWorkspaceFunctionsSchemaNameRoute =
  AppWorkspaceFunctionsSchemaNameRouteImport.update({
    id: '/functions/$schema/$name',
    path: '/functions/$schema/$name',
    getParentRoute: () => AppWorkspaceRoute,
  } as any)
const AppWorkspaceAlterTableSchemaTableRoute =
  AppWorkspaceAlterTableSchemaTableRouteImport.update({
    id: '/alter-table/$schema/$table',
    path: '/alter-table/$schema/$table',
    getParentRoute: () => AppWorkspaceRoute,
  } as any)
const AppWorkspaceTriggersSchemaTableTriggerRoute =
  AppWorkspaceTriggersSchemaTableTriggerRouteImport.update({
    id: '/triggers/$schema/$table/$trigger',
    path: '/triggers/$schema/$table/$trigger',
    getParentRoute: () => AppWorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppWorkspaceIndexRoute
  '/about': typeof AboutRoute
  '/connections': typeof ConnectionsRoute
  '/drivers': typeof DriversRoute
  '/release-notes': typeof ReleaseNotesRoute
  '/settings': typeof SettingsRoute
  '/available-extensions': typeof AppPlainAvailableExtensionsRoute
  '/compare': typeof AppWorkspaceCompareRoute
  '/create-table': typeof AppWorkspaceCreateTableRoute
  '/enums': typeof AppWorkspaceEnumsRoute
  '/er-diagram': typeof AppWorkspaceErDiagramRoute
  '/import': typeof AppWorkspaceImportRoute
  '/query': typeof AppWorkspaceQueryRouteWithChildren
  '/query-builder': typeof AppWorkspaceQueryBuilderRoute
  '/replication': typeof AppWorkspaceReplicationRoute
  '/sequences': typeof AppWorkspaceSequencesRoute
  '/sessions': typeof AppWorkspaceSessionsRoute
  '/extensions/$name': typeof AppWorkspaceExtensionsNameRoute
  '/query/$id': typeof AppWorkspaceQueryIdRoute
  '/users/$name': typeof AppWorkspaceUsersNameRoute
  '/query/': typeof AppWorkspaceQueryIndexRoute
  '/alter-table/$schema/$table': typeof AppWorkspaceAlterTableSchemaTableRoute
  '/functions/$schema/$name': typeof AppWorkspaceFunctionsSchemaNameRoute
  '/matviews/$schema/$name': typeof AppWorkspaceMatviewsSchemaNameRoute
  '/packages/$schema/$name': typeof AppWorkspacePackagesSchemaNameRoute
  '/tables/$schema/$table': typeof AppWorkspaceTablesSchemaTableRoute
  '/view-editor/$schema/$view': typeof AppWorkspaceViewEditorSchemaViewRoute
  '/triggers/$schema/$table/$trigger': typeof AppWorkspaceTriggersSchemaTableTriggerRoute
}
export interface FileRoutesByTo {
  '/': typeof AppWorkspaceIndexRoute
  '/about': typeof AboutRoute
  '/connections': typeof ConnectionsRoute
  '/drivers': typeof DriversRoute
  '/release-notes': typeof ReleaseNotesRoute
  '/settings': typeof SettingsRoute
  '/available-extensions': typeof AppPlainAvailableExtensionsRoute
  '/compare': typeof AppWorkspaceCompareRoute
  '/create-table': typeof AppWorkspaceCreateTableRoute
  '/enums': typeof AppWorkspaceEnumsRoute
  '/er-diagram': typeof AppWorkspaceErDiagramRoute
  '/import': typeof AppWorkspaceImportRoute
  '/query-builder': typeof AppWorkspaceQueryBuilderRoute
  '/replication': typeof AppWorkspaceReplicationRoute
  '/sequences': typeof AppWorkspaceSequencesRoute
  '/sessions': typeof AppWorkspaceSessionsRoute
  '/extensions/$name': typeof AppWorkspaceExtensionsNameRoute
  '/query/$id': typeof AppWorkspaceQueryIdRoute
  '/users/$name': typeof AppWorkspaceUsersNameRoute
  '/query': typeof AppWorkspaceQueryIndexRoute
  '/alter-table/$schema/$table': typeof AppWorkspaceAlterTableSchemaTableRoute
  '/functions/$schema/$name': typeof AppWorkspaceFunctionsSchemaNameRoute
  '/matviews/$schema/$name': typeof AppWorkspaceMatviewsSchemaNameRoute
  '/packages/$schema/$name': typeof AppWorkspacePackagesSchemaNameRoute
  '/tables/$schema/$table': typeof AppWorkspaceTablesSchemaTableRoute
  '/view-editor/$schema/$view': typeof AppWorkspaceViewEditorSchemaViewRoute
  '/triggers/$schema/$table/$trigger': typeof AppWorkspaceTriggersSchemaTableTriggerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/connections': typeof ConnectionsRoute
  '/drivers': typeof DriversRoute
  '/release-notes': typeof ReleaseNotesRoute
  '/settings': typeof SettingsRoute
  '/_app/_plain': typeof AppPlainRouteWithChildren
  '/_app/_workspace': typeof AppWorkspaceRouteWithChildren
  '/_app/_plain/available-extensions': typeof AppPlainAvailableExtensionsRoute
  '/_app/_workspace/compare': typeof AppWorkspaceCompareRoute
  '/_app/_workspace/create-table': typeof AppWorkspaceCreateTableRoute
  '/_app/_workspace/enums': typeof AppWorkspaceEnumsRoute
  '/_app/_workspace/er-diagram': typeof AppWorkspaceErDiagramRoute
  '/_app/_workspace/import': typeof AppWorkspaceImportRoute
  '/_app/_workspace/query': typeof AppWorkspaceQueryRouteWithChildren
  '/_app/_workspace/query-builder': typeof AppWorkspaceQueryBuilderRoute
  '/_app/_workspace/replication': typeof AppWorkspaceReplicationRoute
  '/_app/_workspace/sequences': typeof AppWorkspaceSequencesRoute
  '/_app/_workspace/sessions': typeof AppWorkspaceSessionsRoute
  '/_app/_workspace/': typeof AppWorkspaceIndexRoute
  '/_app/_workspace/extensions/$name': typeof AppWorkspaceExtensionsNameRoute
  '/_app/_workspace/query/$id': typeof AppWorkspaceQueryIdRoute
  '/_app/_workspace/users/$name': typeof AppWorkspaceUsersNameRoute
  '/_app/_workspace/query/': typeof AppWorkspaceQueryIndexRoute
  '/_app/_workspace/alter-table/$schema/$table': typeof AppWorkspaceAlterTableSchemaTableRoute
  '/_app/_workspace/functions/$schema/$name': typeof AppWorkspaceFunctionsSchemaNameRoute
  '/_app/_workspace/matviews/$schema/$name': typeof AppWorkspaceMatviewsSchemaNameRoute
  '/_app/_workspace/packages/$schema/$name': typeof AppWorkspacePackagesSchemaNameRoute
  '/_app/_workspace/tables/$schema/$table': typeof AppWorkspaceTablesSchemaTableRoute
  '/_app/_workspace/view-editor/$schema/$view': typeof AppWorkspaceViewEditorSchemaViewRoute
  '/_app/_workspace/triggers/$schema/$table/$trigger': typeof AppWorkspaceTriggersSchemaTableTriggerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/connections'
    | '/drivers'
    | '/release-notes'
    | '/settings'
    | '/available-extensions'
    | '/compare'
    | '/create-table'
    | '/enums'
    | '/er-diagram'
    | '/import'
    | '/query'
    | '/query-builder'
    | '/replication'
    | '/sequences'
    | '/sessions'
    | '/extensions/$name'
    | '/query/$id'
    | '/users/$name'
    | '/query/'
    | '/alter-table/$schema/$table'
    | '/functions/$schema/$name'
    | '/matviews/$schema/$name'
    | '/packages/$schema/$name'
    | '/tables/$schema/$table'
    | '/view-editor/$schema/$view'
    | '/triggers/$schema/$table/$trigger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/connections'
    | '/drivers'
    | '/release-notes'
    | '/settings'
    | '/available-extensions'
    | '/compare'
    | '/create-table'
    | '/enums'
    | '/er-diagram'
    | '/import'
    | '/query-builder'
    | '/replication'
    | '/sequences'
    | '/sessions'
    | '/extensions/$name'
    | '/query/$id'
    | '/users/$name'
    | '/query'
    | '/alter-table/$schema/$table'
    | '/functions/$schema/$name'
    | '/matviews/$schema/$name'
    | '/packages/$schema/$name'
    | '/tables/$schema/$table'
    | '/view-editor/$schema/$view'
    | '/triggers/$schema/$table/$trigger'
  id:
    | '__root__'
    | '/_app'
    | '/about'
    | '/connections'
    | '/drivers'
    | '/release-notes'
    | '/settings'
    | '/_app/_plain'
    | '/_app/_workspace'
    | '/_app/_plain/available-extensions'
    | '/_app/_workspace/compare'
    | '/_app/_workspace/create-table'
    | '/_app/_workspace/enums'
    | '/_app/_workspace/er-diagram'
    | '/_app/_workspace/import'
    | '/_app/_workspace/query'
    | '/_app/_workspace/query-builder'
    | '/_app/_workspace/replication'
    | '/_app/_workspace/sequences'
    | '/_app/_workspace/sessions'
    | '/_app/_workspace/'
    | '/_app/_workspace/extensions/$name'
    | '/_app/_workspace/query/$id'
    | '/_app/_workspace/users/$name'
    | '/_app/_workspace/query/'
    | '/_app/_workspace/alter-table/$schema/$table'
    | '/_app/_workspace/functions/$schema/$name'
    | '/_app/_workspace/matviews/$schema/$name'
    | '/_app/_workspace/packages/$schema/$name'
    | '/_app/_workspace/tables/$schema/$table'
    | '/_app/_workspace/view-editor/$schema/$view'
    | '/_app/_workspace/triggers/$schema/$table/$trigger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  ConnectionsRoute: typeof ConnectionsRoute
  DriversRoute: typeof DriversRoute
  ReleaseNotesRoute: typeof ReleaseNotesRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/release-notes': {
      id: '/release-notes'
      path: '/release-notes'
      fullPath: '/release-notes'
      preLoaderRoute: typeof ReleaseNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_workspace': {
      id: '/_app/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_plain': {
      id: '/_app/_plain'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppPlainRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_workspace/': {
      id: '/_app/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppWorkspaceIndexRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/_workspace/sessions': {
      id: '/_app/_workspace/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppWorkspaceSessionsRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/_workspace/sequences': {
      id: '/_app/_workspace/sequences'
      path: '/sequences'
      fullPath: '/sequences'
      preLoaderRoute: typeof AppWorkspaceSequencesRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/_workspace/replication': {
      id: '/_app/_workspace/replication'
      path: '/replication'
      fullPath: '/replication'
      preLoaderRoute: typeof AppWorkspaceReplicationRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/_workspace/query-builder': {
      id: '/_app/_workspace/query-builder'
      path: '/query-builder'
      fullPath: '/query-builder'
      preLoaderRoute: typeof AppWorkspaceQueryBuilderRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/_workspace/query': {
      id: '/_app/_workspace/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof AppWorkspaceQueryRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/_workspace/import': {
      id: '/_app/_workspace/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppWorkspaceImportRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/_workspace/er-diagram': {
      id: '/_app/_workspace/er-diagram'
      path: '/er-diagram'
      fullPath: '/er-diagram'
      preLoaderRoute: typeof AppWorkspaceErDiagramRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/_workspace/enums': {
      id: '/_app/_workspace/enums'
      path: '/enums'
      fullPath: '/enums'
      preLoaderRoute: typeof AppWorkspaceEnumsRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/_workspace/create-table': {
      id: '/_app/_workspace/create-table'
      path: '/create-table'
      fullPath: '/create-table'
      preLoaderRoute: typeof AppWorkspaceCreateTableRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/_workspace/compare': {
      id: '/_app/_workspace/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AppWorkspaceCompareRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/_plain/available-extensions': {
      id: '/_app/_plain/available-extensions'
      path: '/available-extensions'
      fullPath: '/available-extensions'
      preLoaderRoute: typeof AppPlainAvailableExtensionsRouteImport
      parentRoute: typeof AppPlainRoute
    }
    '/_app/_workspace/query/': {
      id: '/_app/_workspace/query/'
      path: '/'
      fullPath: '/query/'
      preLoaderRoute: typeof AppWorkspaceQueryIndexRouteImport
      parentRoute: typeof AppWorkspaceQueryRoute
    }
    '/_app/_workspace/users/$name': {
      id: '/_app/_workspace/users/$name'
      path: '/users/$name'
      fullPath: '/users/$name'
      preLoaderRoute: typeof AppWorkspaceUsersNameRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/_workspace/query/$id': {
      id: '/_app/_workspace/query/$id'
      path: '/$id'
      fullPath: '/query/$id'
      preLoaderRoute: typeof AppWorkspaceQueryIdRouteImport
      parentRoute: typeof AppWorkspaceQueryRoute
    }
    '/_app/_workspace/extensions/$name': {
      id: '/_app/_workspace/extensions/$name'
      path: '/extensions/$name'
      fullPath: '/extensions/$name'
      preLoaderRoute: typeof AppWorkspaceExtensionsNameRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/_workspace/view-editor/$schema/$view': {
      id: '/_app/_workspace/view-editor/$schema/$view'
      path: '/view-editor/$schema/$view'
      fullPath: '/view-editor/$schema/$view'
      preLoaderRoute: typeof AppWorkspaceViewEditorSchemaViewRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/_workspace/tables/$schema/$table': {
      id: '/_app/_workspace/tables/$schema/$table'
      path: '/tables/$schema/$table'
      fullPath: '/tables/$schema/$table'
      preLoaderRoute: typeof AppWorkspaceTablesSchemaTableRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/_workspace/packages/$schema/$name': {
      id: '/_app/_workspace/packages/$schema/$name'
      path: '/packages/$schema/$name'
      fullPath: '/packages/$schema/$name'
      preLoaderRoute: typeof AppWorkspacePackagesSchemaNameRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/_workspace/matviews/$schema/$name': {
      id: '/_app/_workspace/matviews/$schema/$name'
      path: '/matviews/$schema/$name'
      fullPath: '/matviews/$schema/$name'
      preLoaderRoute: typeof AppWorkspaceMatviewsSchemaNameRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/_workspace/functions/$schema/$name': {
      id: '/_app/_workspace/functions/$schema/$name'
      path: '/functions/$schema/$name'
      fullPath: '/functions/$schema/$name'
      preLoaderRoute: typeof AppWorkspaceFunctionsSchemaNameRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/_workspace/alter-table/$schema/$table': {
      id: '/_app/_workspace/alter-table/$schema/$table'
      path: '/alter-table/$schema/$table'
      fullPath: '/alter-table/$schema/$table'
      preLoaderRoute: typeof AppWorkspaceAlterTableSchemaTableRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/_workspace/triggers/$schema/$table/$trigger': {
      id: '/_app/_workspace/triggers/$schema/$table/$trigger'
      path: '/triggers/$schema/$table/$trigger'
      fullPath: '/triggers/$schema/$table/$trigger'
      preLoaderRoute: typeof AppWorkspaceTriggersSchemaTableTriggerRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
  }
}

interface AppPlainRouteChildren {
  AppPlainAvailableExtensionsRoute: typeof AppPlainAvailableExtensionsRoute
}

const AppPlainRouteChildren: AppPlainRouteChildren = {
  AppPlainAvailableExtensionsRoute: AppPlainAvailableExtensionsRoute,
}

const AppPlainRouteWithChildren = AppPlainRoute._addFileChildren(
  AppPlainRouteChildren,
)

interface AppWorkspaceQueryRouteChildren {
  AppWorkspaceQueryIdRoute: typeof AppWorkspaceQueryIdRoute
  AppWorkspaceQueryIndexRoute: typeof AppWorkspaceQueryIndexRoute
}

const AppWorkspaceQueryRouteChildren: AppWorkspaceQueryRouteChildren = {
  AppWorkspaceQueryIdRoute: AppWorkspaceQueryIdRoute,
  AppWorkspaceQueryIndexRoute: AppWorkspaceQueryIndexRoute,
}

const AppWorkspaceQueryRouteWithChildren =
  AppWorkspaceQueryRoute._addFileChildren(AppWorkspaceQueryRouteChildren)

interface AppWorkspaceRouteChildren {
  AppWorkspaceCompareRoute: typeof AppWorkspaceCompareRoute
  AppWorkspaceCreateTableRoute: typeof AppWorkspaceCreateTableRoute
  AppWorkspaceEnumsRoute: typeof AppWorkspaceEnumsRoute
  AppWorkspaceErDiagramRoute: typeof AppWorkspaceErDiagramRoute
  AppWorkspaceImportRoute: typeof AppWorkspaceImportRoute
  AppWorkspaceQueryRoute: typeof AppWorkspaceQueryRouteWithChildren
  AppWorkspaceQueryBuilderRoute: typeof AppWorkspaceQueryBuilderRoute
  AppWorkspaceReplicationRoute: typeof AppWorkspaceReplicationRoute
  AppWorkspaceSequencesRoute: typeof AppWorkspaceSequencesRoute
  AppWorkspaceSessionsRoute: typeof AppWorkspaceSessionsRoute
  AppWorkspaceIndexRoute: typeof AppWorkspaceIndexRoute
  AppWorkspaceExtensionsNameRoute: typeof AppWorkspaceExtensionsNameRoute
  AppWorkspaceUsersNameRoute: typeof AppWorkspaceUsersNameRoute
  AppWorkspaceAlterTableSchemaTableRoute: typeof AppWorkspaceAlterTableSchemaTableRoute
  AppWorkspaceFunctionsSchemaNameRoute: typeof AppWorkspaceFunctionsSchemaNameRoute
  AppWorkspaceMatviewsSchemaNameRoute: typeof AppWorkspaceMatviewsSchemaNameRoute
  AppWorkspacePackagesSchemaNameRoute: typeof AppWorkspacePackagesSchemaNameRoute
  AppWorkspaceTablesSchemaTableRoute: typeof AppWorkspaceTablesSchemaTableRoute
  AppWorkspaceViewEditorSchemaViewRoute: typeof AppWorkspaceViewEditorSchemaViewRoute
  AppWorkspaceTriggersSchemaTableTriggerRoute: typeof AppWorkspaceTriggersSchemaTableTriggerRoute
}

const AppWorkspaceRouteChildren: AppWorkspaceRouteChildren = {
  AppWorkspaceCompareRoute: AppWorkspaceCompareRoute,
  AppWorkspaceCreateTableRoute: AppWorkspaceCreateTableRoute,
  AppWorkspaceEnumsRoute: AppWorkspaceEnumsRoute,
  AppWorkspaceErDiagramRoute: AppWorkspaceErDiagramRoute,
  AppWorkspaceImportRoute: AppWorkspaceImportRoute,
  AppWorkspaceQueryRoute: AppWorkspaceQueryRouteWithChildren,
  AppWorkspaceQueryBuilderRoute: AppWorkspaceQueryBuilderRoute,
  AppWorkspaceReplicationRoute: AppWorkspaceReplicationRoute,
  AppWorkspaceSequencesRoute: AppWorkspaceSequencesRoute,
  AppWorkspaceSessionsRoute: AppWorkspaceSessionsRoute,
  AppWorkspaceIndexRoute: AppWorkspaceIndexRoute,
  AppWorkspaceExtensionsNameRoute: AppWorkspaceExtensionsNameRoute,
  AppWorkspaceUsersNameRoute: AppWorkspaceUsersNameRoute,
  AppWorkspaceAlterTableSchemaTableRoute:
    AppWorkspaceAlterTableSchemaTableRoute,
  AppWorkspaceFunctionsSchemaNameRoute: AppWorkspaceFunctionsSchemaNameRoute,
  AppWorkspaceMatviewsSchemaNameRoute: AppWorkspaceMatviewsSchemaNameRoute,
  AppWorkspacePackagesSchemaNameRoute: AppWorkspacePackagesSchemaNameRoute,
  AppWorkspaceTablesSchemaTableRoute: AppWorkspaceTablesSchemaTableRoute,
  AppWorkspaceViewEditorSchemaViewRoute: AppWorkspaceViewEditorSchemaViewRoute,
  AppWorkspaceTriggersSchemaTableTriggerRoute:
    AppWorkspaceTriggersSchemaTableTriggerRoute,
}

const AppWorkspaceRouteWithChildren = AppWorkspaceRoute._addFileChildren(
  AppWorkspaceRouteChildren,
)

interface AppRouteChildren {
  AppPlainRoute: typeof AppPlainRouteWithChildren
  AppWorkspaceRoute: typeof AppWorkspaceRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppPlainRoute: AppPlainRouteWithChildren,
  AppWorkspaceRoute: AppWorkspaceRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  ConnectionsRoute: ConnectionsRoute,
  DriversRoute: DriversRoute,
  ReleaseNotesRoute: ReleaseNotesRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
