/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppQueryRouteImport } from './routes/_app.query'
import { Route as AppAboutRouteImport } from './routes/_app.about'
import { Route as AppQueryIndexRouteImport } from './routes/_app.query.index'
import { Route as AppQueryIdRouteImport } from './routes/_app.query.$id'
import { Route as AppTablesSchemaTableRouteImport } from './routes/_app.tables.$schema.$table'

const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppQueryRoute = AppQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppQueryIndexRoute = AppQueryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppQueryRoute,
} as any)
const AppQueryIdRoute = AppQueryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppQueryRoute,
} as any)
const AppTablesSchemaTableRoute = AppTablesSchemaTableRouteImport.update({
  id: '/tables/$schema/$table',
  path: '/tables/$schema/$table',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/connections': typeof ConnectionsRoute
  '/about': typeof AppAboutRoute
  '/query': typeof AppQueryRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/query/$id': typeof AppQueryIdRoute
  '/query/': typeof AppQueryIndexRoute
  '/tables/$schema/$table': typeof AppTablesSchemaTableRoute
}
export interface FileRoutesByTo {
  '/connections': typeof ConnectionsRoute
  '/about': typeof AppAboutRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/query/$id': typeof AppQueryIdRoute
  '/query': typeof AppQueryIndexRoute
  '/tables/$schema/$table': typeof AppTablesSchemaTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/connections': typeof ConnectionsRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/query': typeof AppQueryRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/query/$id': typeof AppQueryIdRoute
  '/_app/query/': typeof AppQueryIndexRoute
  '/_app/tables/$schema/$table': typeof AppTablesSchemaTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connections'
    | '/about'
    | '/query'
    | '/settings'
    | '/query/$id'
    | '/query/'
    | '/tables/$schema/$table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connections'
    | '/about'
    | '/settings'
    | '/'
    | '/query/$id'
    | '/query'
    | '/tables/$schema/$table'
  id:
    | '__root__'
    | '/_app'
    | '/connections'
    | '/_app/about'
    | '/_app/query'
    | '/_app/settings'
    | '/_app/'
    | '/_app/query/$id'
    | '/_app/query/'
    | '/_app/tables/$schema/$table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ConnectionsRoute: typeof ConnectionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/query': {
      id: '/_app/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof AppQueryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/query/': {
      id: '/_app/query/'
      path: '/'
      fullPath: '/query/'
      preLoaderRoute: typeof AppQueryIndexRouteImport
      parentRoute: typeof AppQueryRoute
    }
    '/_app/query/$id': {
      id: '/_app/query/$id'
      path: '/$id'
      fullPath: '/query/$id'
      preLoaderRoute: typeof AppQueryIdRouteImport
      parentRoute: typeof AppQueryRoute
    }
    '/_app/tables/$schema/$table': {
      id: '/_app/tables/$schema/$table'
      path: '/tables/$schema/$table'
      fullPath: '/tables/$schema/$table'
      preLoaderRoute: typeof AppTablesSchemaTableRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppQueryRouteChildren {
  AppQueryIdRoute: typeof AppQueryIdRoute
  AppQueryIndexRoute: typeof AppQueryIndexRoute
}

const AppQueryRouteChildren: AppQueryRouteChildren = {
  AppQueryIdRoute: AppQueryIdRoute,
  AppQueryIndexRoute: AppQueryIndexRoute,
}

const AppQueryRouteWithChildren = AppQueryRoute._addFileChildren(
  AppQueryRouteChildren,
)

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppQueryRoute: typeof AppQueryRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTablesSchemaTableRoute: typeof AppTablesSchemaTableRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppQueryRoute: AppQueryRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppTablesSchemaTableRoute: AppTablesSchemaTableRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ConnectionsRoute: ConnectionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
