/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TablesSchemaTableRouteImport } from './routes/tables.$schema.$table'

const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesSchemaTableRoute = TablesSchemaTableRouteImport.update({
  id: '/tables/$schema/$table',
  path: '/tables/$schema/$table',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connections': typeof ConnectionsRoute
  '/tables/$schema/$table': typeof TablesSchemaTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connections': typeof ConnectionsRoute
  '/tables/$schema/$table': typeof TablesSchemaTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connections': typeof ConnectionsRoute
  '/tables/$schema/$table': typeof TablesSchemaTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/connections' | '/tables/$schema/$table'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/connections' | '/tables/$schema/$table'
  id: '__root__' | '/' | '/about' | '/connections' | '/tables/$schema/$table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConnectionsRoute: typeof ConnectionsRoute
  TablesSchemaTableRoute: typeof TablesSchemaTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables/$schema/$table': {
      id: '/tables/$schema/$table'
      path: '/tables/$schema/$table'
      fullPath: '/tables/$schema/$table'
      preLoaderRoute: typeof TablesSchemaTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConnectionsRoute: ConnectionsRoute,
  TablesSchemaTableRoute: TablesSchemaTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
